---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: rest-fights
    application: fights-service
    system: quarkus-super-heroes
  name: rest-fights-config-creds
data:
  quarkus.mongodb.credentials.username: c3VwZXJmaWdodA==
  quarkus.mongodb.credentials.password: c3VwZXJmaWdodA==
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: fights-db
    application: fights-service
    system: quarkus-super-heroes
  name: fights-db-config
data:
  MONGO_INITDB_DATABASE: ZmlnaHRz
  MONGO_INITDB_ROOT_USERNAME: c3VwZXI=
  MONGO_INITDB_ROOT_PASSWORD: c3VwZXI=
type: Opaque
