---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/vcs-ref: main
    app.quarkus.io/vcs-url: https://github.com/quarkusio/quarkus-super-heroes
    app.openshift.io/connects-to: otel-lgtm
    app.quarkus.io/quarkus-version: 3.36.1
    app.quarkus.io/vcs-uri: https://github.com/quarkusio/quarkus-super-heroes.git
    app.quarkus.io/build-timestamp: 2026-06-08 - 17:31:53 +0000
  labels:
    app.kubernetes.io/name: rest-narration
    app.kubernetes.io/part-of: narration-service
    app.kubernetes.io/version: java21-latest
    app: rest-narration
    application: narration-service
    system: quarkus-super-heroes
    app.kubernetes.io/managed-by: quarkus
  name: rest-narration
spec:
  ports:
    - name: http
      nodePort: 31286
      port: 80
      protocol: TCP
      targetPort: {{ .Values.app.ports.http }}
  selector:
    app.kubernetes.io/name: rest-narration
    app.kubernetes.io/part-of: narration-service
    app.kubernetes.io/version: java21-latest
  type: NodePort
