---
apiVersion: v2
name: super-heroes-fights
description: Quarkus Super Heroes - Fights service with all downstream dependencies
version: "1.0.0"
dependencies:
  - name: rest-fights
    version: "*"
    repository: "file://../minikube"
  - name: rest-villains
    version: "*"
    repository: "file://../../../rest-villains/deploy/helm/minikube"
  - name: rest-heroes
    version: "*"
    repository: "file://../../../rest-heroes/deploy/helm/minikube"
  - name: rest-narration
    version: "*"
    repository: "file://../../../rest-narration/deploy/helm/minikube"
  - name: grpc-locations
    version: "*"
    repository: "file://../../../grpc-locations/deploy/helm/minikube"
