#!/usr/bin/env bash
set -e

for project in "event-statistics" "rest-fights" "rest-heroes" "rest-villains"
do
  $project/mvnw -f $project/pom.xml --settings .github/quarkus-ecosystem-maven-settings.xml -B clean verify -Dquarkus.platform.group-id=io.quarkus -Dquarkus.platform.version=${QUARKUS_VERSION}
done
