#!/usr/bin/env bash
set -e

run_build() {
  local java_version=$1

  for project in "event-statistics" "rest-fights" "rest-heroes" "rest-villains"
  do
    $project/mvnw -f $project/pom.xml \
      --settings .github/quarkus-ecosystem-maven-settings.xml \
      -B clean verify \
      -Dquarkus.platform.group-id=io.quarkus \
      -Dquarkus.platform.version=${QUARKUS_VERSION} \
      -Dquarkus.http.host=0.0.0.0 \
      -Dmaven.compiler.release=$java_version
  done
}

echo "Running build for Java 11"
echo "JAVA_HOME=${JAVA_HOME}"
run_build 11

# Now do it again for Java 17
JAVA_HOME=../${JAVA_17_PATH}

echo "Running build for Java 17"
echo "JAVA_HOME=${JAVA_HOME}"
run_build 17
