---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/vcs-ref: main
    app.quarkus.io/vcs-url: https://github.com/quarkusio/quarkus-super-heroes
    app.openshift.io/connects-to: "rest-fights,otel-lgtm"
    app.quarkus.io/quarkus-version: 3.37.3
    app.quarkus.io/vcs-uri: https://github.com/quarkusio/quarkus-super-heroes.git
    app.quarkus.io/build-timestamp: 2026-07-22 - 02:43:09 +0000
  labels:
    app.kubernetes.io/name: ui-super-heroes
    app.kubernetes.io/part-of: ui-super-heroes
    app.kubernetes.io/version: java25-latest
    app: ui-super-heroes
    application: ui-super-heroes
    system: quarkus-super-heroes
    app.kubernetes.io/managed-by: quarkus
  name: ui-super-heroes
spec:
  ports:
    - name: http
      nodePort: 30904
      port: 80
      protocol: TCP
      targetPort: {{ .Values.app.ports.http }}
  selector:
    app.kubernetes.io/name: ui-super-heroes
    app.kubernetes.io/part-of: ui-super-heroes
    app.kubernetes.io/version: java25-latest
  type: NodePort
