
  fights-db:
    image: mongo:8
    container_name: fights-db
    ports:
      - "27017"
    environment:
      MONGO_INITDB_DATABASE: fights
      MONGO_INITDB_ROOT_USERNAME: super
      MONGO_INITDB_ROOT_PASSWORD: super
    volumes:
      - ../../../rest-fights/deploy/db-init/initialize-database.js:/docker-entrypoint-initdb.d/1-init-db.js

  apicurio:
    image: quay.io/apicurio/apicurio-registry:3.1.7
    container_name: apicurio
    ports:
      - "8086:8086"
    environment:
      REGISTRY_AUTH_ANONYMOUS_READ_ACCESS_ENABLED: "true"
      QUARKUS_HTTP_PORT: 8086

  fights-kafka:
    image: apache/kafka-native:4.2.0
    container_name: fights-kafka
    depends_on:
      - apicurio
    ports:
      - "9092:9092"
    environment:
      LOG_DIR: /tmp/logs
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://fights-kafka:9092
      KAFKA_NODE_ID: "1"
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
