-- A 100 record random sample from https://github.com/quarkusio/quarkus-supes/blob/characterdata/all-heroes.sql
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'The Flash', 'Jay Garrick', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/jay-garrick-6169553426034869748.jpg', 'AgilityDurabilityIntelligenceReflexesStaminaSuper SpeedAccelerated HealingAuraDimensional TravelElectricity AbsorptionElectrokinesisEnergy BlastsEnergy ManipulationEnhanced MemoryEnhanced SensesForce FieldsHeat GenerationIndomitable WillInvisibilityLongevityMaster TacticianPhasingSpatial AwarenessJumpWind Control', 6000);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Terrance', 'Terrence', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/terrence-8580751879099466472.jpg', 'Social InfluencingJumpToxin and Disease ControlToxin and Disease Resistance', 5);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Baptiste', 'Jean-Baptiste Augustin', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/jean-baptiste-augustin-8419899297910243506.jpg', 'Accelerated HealingAgilityDamage BoostDamage ReductionDurabilityIntelligenceWeapons Master', 22);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Silk', 'Cindy Moon', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/cindy-moon--4597750225317770283.jpg', 'AcrobaticsAgilityDanger SenseDexterityEndurancePrecognitionReflexesStaminaStealthSurface ScalingVehicular MasteryWallcrawlingWeb CreationAccelerated HealingAnimal AttributesAnimal Oriented PowersAudio ControlCloth ManipulationDisguise MasteryEnhanced HearingEnhanced SensesEnhanced SightEnhanced SmellEnhanced TouchHeat ResistanceJumpMaster Martial ArtistNatural WeaponsRadar SenseSubstance SecretionToxin and Disease ResistanceVision - NightWeapons MasterRadiation ImmunityRegeneration', 171);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Rogue Cheney', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/rogue-cheney-4581925125354899965.jpg', 'AgilityEnhanced SensesExtrasensory PerceptionIntangibilityMagicMaster Martial ArtistNon-Physical InteractionReflexesSuper BreathUmbrakinesisWeapons Master', 1000);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Supergirl', 'Kara Zor-El', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/kara-zor-el--3427342339139678445.jpg', 'AgilityEnergy AbsorptionEnhanced HearingEnhanced SightFlightInvulnerabilityLongevityReflexesStaminaSuper BreathSuper SpeedSuper StrengthVision - HeatVision - InfraredVision - MicroscopicVision - TelescopicVision - X-RayBone ManipulationCryokinesisElement ControlTelekinesisTelepathy Resistance', 6000);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Alucard', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/alucard-6502300089792219791.jpg', 'Accelerated HealingAcrobaticsAgilityBlood ManipulationBloodlustCold ResistanceCryokinesisDarkforce ManipulationDexterityDurabilityDurability NegationElemental TransmogrificationEnduranceEnergy ManipulationEnergy ResistanceEnhanced HearingEnhanced MemoryEnhanced SensesEnhanced SightEnhanced SmellEnhanced TouchFear ManipulationHeat ResistanceImmortalityIntelligenceInvulnerabilityJumpLevitationLuckMagicMaster Martial ArtistMaster TacticianRadiation AbsorptionRadiation ControlRadiation ImmunityReflexesRegenerationRegeneration NegationSealingShapeshiftingSoul ManipulationSoul ResistanceStaminaStatistics AmplificationSuper SpeedSuper StrengthSwordsmanshipTime ManipulationToxin and Disease ControlToxin and Disease ResistanceWeapons MasterAcid ResistantsAir ControlAnimal ControlAttack ReflectionBerserk ModeCausality ResistanceClairvoyance ResistanceCorruption ResistanceCurse ResistanceDamage BoostElectricity ResistanceElectrokinesisElement ControlFire ControlFire ResistanceFlightForce FieldsHeat GenerationHellfire ManipulationHellfire ResistanceHoly ManipulationHoly ResistanceIllusion ResistanceImmortality NegationIndomitable WillInformation AnalysisIntangibilityLight ControlMagic ResistanceMind Control ResistanceNon-Physical InteractionPetrificationPossession ResistancePower NullifierPrecognitionReality Warping ResistanceResurrectionSelf-SustenanceSound ManipulationSummoningTelepathyTelepathy ResistanceTeleportationTime Manipulation ResistanceTimeframe ControlTransmutationUnholy ResistanceWeapon Summoning', 2000000);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Recca Hanabishi', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/recca-hanabishi-5628238309286887617.jpg', 'Fire ControlFire ResistanceForce FieldsPower Absorption ImmunitySoul ManipulationAccelerated DevelopmentAcrobaticsEnergy ManipulationEnhanced SensesExtrasensory PerceptionHealIllusionsImmortalityMagicNon-Physical InteractionRegenerationResurrectionStealthWeapons Master', 1000);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Invader Zim', 'Zim', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/zim--4121277570101524125.jpg', 'Disguise MasteryDurabilityHackingInsanityIntelligencePeak Human ConditionPower SuitPreparationSelf-SustenanceStaminaStealthSuper SpeedSuper StrengthVehicular MasteryAccelerated HealingAcrobaticsAdaptationAgilityCold ResistanceCosmic AwarenessDanger SenseDexterityEnduranceEnhanced SensesExplosion ManipulationFlightForce FieldsHeat ResistanceInformation AnalysisJumpLongevityMarksmanshipRadar SenseReflexesSpaceflightVision - NightWeapons MasterCausality ManipulationCloningDimensional TravelElasticityIndomitable WillMemory ManipulationMind ControlSpatial ManipulationStatistics AmplificationTeleportationToon ForceTransmutation', 2000);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Yui Kodai', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/yui-kodai-8979721139911411519.jpg', 'IntelligenceMatter Manipulation', 72);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Yuu Otosaka', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/yuu-otosaka--2388977000261270090.jpg', 'Power AbsorptionPower MimicryPossession', 64);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Mei Hatsume', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/mei-hatsume--7164892666964196814.jpg', 'Enhanced SightIntelligenceVision - TelescopicInformation Analysis', 19);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Spinel (reset)', 'Spinel', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/spinel-4866272966721621285.jpg', 'AgilityDurabilityElasticityImmortalityInorganic PhysiologyJumpSelf-SustenanceToon ForceEnhanced MemoryHeat ResistanceShapeshiftingSize ChangingSupernatural ConditionGlidingMultiple PersonalitiesReflexes', 435);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Alison Angel', 'Allison Pendle', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/allison-pendle--3644270388175287771.jpg', 'Intuitive aptitudePeak Human ConditionToxin and Disease ResistanceEmpathyEnduranceInformation AnalysisLongevityMaster TacticianWeapons MasterIndomitable WillMaster Martial ArtistMechanical Aptitude', 12);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Asha Barlow', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/asha-barlow--354430142425053481.jpg', 'IntelligenceEnduranceIndomitable Will', 8);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Obsidian', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/obsidian--4897683337523739089.jpg', 'Darkforce ManipulationDurabilityEnergy ConstructsEnergy EmbodimentFlightIntangibilityIntelligenceMadness ManipulationPhasingShadow ManipulationStaminaSuper SpeedSuper StrengthUmbrakinesisAbsorptionAccelerated HealingAgilityAttack ReflectionCold ResistanceDensity ControlElectricity AbsorptionElectricity ResistanceElemental TransmogrificationEnergy AbsorptionEnergy BeamsEnergy BlastsEnergy ResistanceEnhanced SensesEnhanced SightForce FieldsHeat ResistanceInterstellar TravelInvulnerabilityLevitationPortal CreationPossessionReflexesRegenerationSize ChangingSpace SurvivabilityTeleportationToxin and Disease ResistanceReality Warping ResistanceSoul ManipulationTelepathyVehicular Mastery', 25000);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Veil', 'Maddy Berry', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/maddy-berry--1879239256908477418.jpg', 'IntangibilityInvisibilityStealthDensity ControlElemental TransmogrificationFlightPossessionSubstance SecretionTransformation', 66);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Miss Martian', 'M''gann M''orzz', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/m''gann-m''orzz--6053125006563653207.jpg', 'DurabilityIntelligenceLevitationSuper SpeedSuper StrengthTelepathyCamouflageCold ResistanceDensity ControlElasticityEnhanced SensesFlightIllusion ResistanceIllusionsIntangibilityInvisibilityMemory ManipulationMind BlastMind ControlMind Control ResistancePhasingShapeshiftingTelekinesisToxin and Disease Resistance', 1000);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'War Machine', 'James Rhodes', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/james-rhodes--318235078902657254.jpg', 'DurabilityAgilityCold ResistanceElectricity AbsorptionElectricity ResistanceEnergy AbsorptionEnergy BeamsEnergy ResistanceExplosion ManipulationFire ControlFire ResistanceFlightHeat ResistanceHoming AttackLevitationMaster Martial ArtistPower SuitRadar SenseVision - NightVision - TelescopicVision - X-RayWeapon-based PowersWeapons Master', 222);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Kid', 'Death The Kid', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/death-the-kid-9188607300138583592.jpg', 'AcrobaticsAgilityMadness ManipulationMind ControlWeapons MasterBody PuppetryEnhanced SensesExistence Erasure ResistanceExtrasensory PerceptionFlightForce FieldsInsanityMagicNon-Physical InteractionRegenerationSoul ManipulationStatistics Amplification', 1000);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Nabu', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/nabu-845304778304473288.jpg', 'AbsorptionAccelerated HealingAdaptationAfterimage CreationAgilityAir ControlAnimal ControlAntimatter ManipulationArcane MagicAstral ProjectionAstral TrapAstral TravelAttack NegationAttack ReflectionAvatar CreationBanishBlood ManipulationBullet TimeCausality ManipulationCausality ResistanceClairvoyanceClairvoyance ResistanceCloakingCold ResistanceCorruption ResistanceCosmic AwarenessCreationDanger SenseDimensional AwarenessDimensional TravelDuplicationDurabilityElectrical TransportElectricity AbsorptionElectricity ResistanceElectro-Magnetism ManipulationElectrokinesisElement ControlElemental TransmogrificationEmpathyEnduranceEnergy AbsorptionEnergy ArmorEnergy BeamsEnergy BlastsEnergy ConstructsEnergy EmbodimentEnergy ManipulationEnergy ResistanceEnhanced HearingEnhanced MemoryEnhanced SensesEnhanced SightEnhanced SmellEnhanced TouchFate ManipulationFire ControlFire ResistanceFlightForce FieldsGravity ControlHeat GenerationHeat ResistanceHellfire ResistanceHoming AttackIlluminationIllusionsImmortalityIntangibilityIntelligenceInterstellar TravelInvisibilityInvulnerabilityLevitationLongevityMagicMagic AbsorptionMagic ResistanceMagnetismMatter ManipulationMemory ManipulationMind BlastMind ControlMind Control ResistanceMind TransferMolecular CombustionMolecular DissipationMolecular ImmobilizationMolecular ManipulationMolecular OscillationNecromancyNon-CorporealNon-Physical InteractionParalysisPhasingPocket DimensionsPortal CreationPossessionPossession ResistancePostcognitionPower AbsorptionPower Absorption ImmunityPower AugmentationPower BestowalPower SuitPrecognitionPreparationProjectionPsionic PowersPsychometryPurificationRadar SenseRadiation AbsorptionRadiation ControlRadiation ImmunityReactive EvolutionReactive Power LevelReality WarpingReflexesRegenerationResurrectionSelf-SustenanceShapeshiftingSoul ManipulationSoul ResistanceSpaceflightSpatial ManipulationStaminaSummoningSuper SpeedSuper StrengthTelekinesisTelepathyTelepathy ResistanceTeleportationTime ManipulationTime Manipulation ResistanceTime TravelTimeframe ControlTransformationTransmutationVitakinesisWater ControlWeather ControlWind ControlAccelerated DevelopmentAcrobaticsAnti-GravityConceptual ManipulationDamage BoostDamage ReductionDamage TransferalDark MagicDimension StorageDurability NegationExistence ErasureExistence Erasure ResistanceFate ResistanceFood ManipulationHigher Dimensional ManipulationIllusion ResistanceLarge SizeMatter AbsorptionPlant ControlReality Warping ResistanceSize ChangingSpatial AwarenessSpatial CommunicationWillpower Manipulation', 192000000);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Unworthy Thor', 'Thor Odinson', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/thor-odinson--143464674194079057.jpg', 'AgilityDexterityEnduranceMaster Martial ArtistMaster TacticianPeak Human ConditionReflexesStaminaWeapons Master', 49);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Madoka', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/madoka--2042951982777612760.jpg', 'Animal AttributesDurabilityEnduranceInstinctive ReactionReflexesSuper SpeedSuper StrengthSupernatural ConditionAccelerated HealingAgilityDexterityEnhanced SensesGrappling/ClimbingLongevityNatural ArmorNatural WeaponsTransformationBerserk ModeBloodlustCold ResistanceEnergy ResistanceEnhanced HearingEnhanced SightEnhanced SmellFire ResistanceHeat ResistanceLarge SizeNanotechnologyPower SenseToxin and Disease Resistance', 76);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Nick Morton (Power Of Set)', 'Nicholas Morton', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/nicholas-morton--8423429082334018606.jpg', 'Accelerated HealingAnimal ControlDurabilityEnhanced SensesIntelligenceStaminaStealthSuper SpeedSuper StrengthWind ControlAgilityAstral ProjectionAuraClairvoyanceCloakingCold ResistanceDeath ManipulationEmpathyEnduranceFire ResistanceGrim ReapingHeat ResistanceImmortalityJumpLife ManipulationMind ControlMind Control ResistancePossession ResistancePower BestowalPsionic PowersRadiation ImmunityReflexesRegenerationResurrectionSoul ManipulationSoul ResistanceTeleportationToxin and Disease ResistanceVitakinesisWeather ControlAnimal Oriented PowersMemory ManipulationPower AugmentationToxin and Disease Control', 16000);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Vulcan', 'Gabriel Summers', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/gabriel-summers--2919016231429648567.jpg', 'AbsorptionAccelerated HealingAuraCold ResistanceDexterityDurabilityElectricity ResistanceEnduranceEnergy AbsorptionEnergy ArmorEnergy BeamsEnergy BlastsEnergy ConstructsEnergy EmbodimentEnergy ManipulationEnergy ResistanceFlightHealHeat GenerationHeat ResistanceImmortalityInvulnerabilityPower AbsorptionPsionic PowersRadiation ImmunityReflexesSelf-SustenanceSpaceflightStaminaSuper SpeedSuper StrengthTelekinesisToxin and Disease ResistanceUnderwater breathingAdaptationAgilityBerserk ModeElectricity AbsorptionElectrokinesisFire ResistanceHellfire ResistanceJumpLight ControlMaster TacticianMind Control ResistancePain SuppressionPower SenseRegenerationSpatial AwarenessTelepathy ResistanceVision - Heat', 117000);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Speedy', 'Roy Harper', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/roy-harper--3427801961221832556.jpg', 'AcrobaticsAgilityDurabilityEnduranceIntelligenceMarksmanshipMaster Martial ArtistPeak Human ConditionStaminaStealthDexterityEnhanced HearingEnhanced SensesEnhanced SightJumpMaster TacticianReflexesWeapons Master', 71);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Speedy', 'Mia Dearden', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/mia-dearden--8564232398732901788.jpg', 'AcrobaticsAgilityDisguise MasteryMarksmanshipMaster Martial ArtistReflexesStaminaSwordsmanshipDexterityEnduranceHackingLongevityMaster TacticianVehicular MasteryWeapons Master', 48);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'SCP-054', 'Water Nymph', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/water-nymph-7103875879033916658.jpg', 'Liquid TransmutationUnderwater breathingBerserk ModeImmortalityLongevityWater ControlIntangibility', 51);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'The Machine', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/the-machine--932941039468523604.jpg', 'Enhanced MemoryIntelligenceMaster TacticianStealthTechnological PossessionPrecognition', 468);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Lilith', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/lilith--4218735510820205685.jpg', 'Cold ResistanceDurabilityEnduranceFire ControlFire ResistanceHealHeat GenerationHeat ResistanceJumpNatural ArmorNatural WeaponsPeak Human ConditionStaminaSuper SpeedSuper StrengthAccelerated DevelopmentAccelerated HealingAcrobaticsAgilityBullet TimeDexterityElectricity ResistanceIndomitable WillInvulnerabilityLatent AbilitiesLongevityMaster Martial ArtistReflexesRegenerationSize Changing', 562);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Ellie Bartowski', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/ellie-bartowski-4968107830775598992.jpg', 'HealIntelligencePeak Human ConditionStaminaEndurance', 6);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Striker Eureka', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/striker-eureka-3381009467982366771.jpg', 'Cold ResistanceEnduranceEnhanced SightExplosion ManipulationHeat ResistanceInvulnerabilityLarge SizeSelf-SustenanceToxin and Disease ResistanceWeapon-based PowersAgilityDexterityElectricity ResistanceEnhanced SensesHeat GenerationHoming AttackMarksmanshipRadar SenseReflexesSelf-DestructionSpatial AwarenessDamage BoostEnergy ResistanceMaster Martial ArtistMultiple PersonalitiesRadiation ImmunityWeapons Master', 864);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Invisible Girl', 'Toru Hagakure', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/toru-hagakure--7748805074238814077.jpg', 'InvisibilityStealthLight Control', 33);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Kid Flash', 'Bart Allen', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/bart-allen-4431455915262756218.jpg', 'AdaptationAfterimage CreationAgilityAir ControlAuraBullet TimeDexterityElectrokinesisEnduranceEnhanced HearingEnhanced MemoryEnhanced SensesEnhanced SightHeat GenerationHeat ResistanceIntangibilityIntelligenceJumpPhasingPortal CreationReflexesSpeed ForceStaminaVortex CreationWind ControlAccelerated HealingCold ResistanceDimensional TravelElemental TransmogrificationEnergy AbsorptionEnergy BlastsEnergy ManipulationForce FieldsIlluminationInvisibilityMolecular ManipulationPower AugmentationRegenerationSelf-SustenanceTeleportationTimeframe ControlVibration ManipulationTime ManipulationTime Manipulation ResistanceTime Travel', 131000);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Blue Dragon', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/blue-dragon--8030152065634384060.jpg', 'AcrobaticsAgilityAnimal AttributesChi ManipulationDexterityDurabilityIndomitable WillJumpMarksmanshipMaster Martial ArtistMaster TacticianPeak Human ConditionStaminaSuper SpeedSuper StrengthAccelerated DevelopmentAuraBullet TimeEnduranceEnergy BeamsEnergy BlastsEnergy ManipulationEnhanced HearingEnhanced SensesEnhanced SightEnhanced SmellFire ResistanceFlightInvulnerabilityLight ControlNatural ArmorNatural WeaponsReflexes', 545);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Bloodshot', 'Raymond Garrison', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/raymond-garrison-7994734955792779156.jpg', 'Accelerated HealingDurabilityEnduranceEnhanced SensesNanotechnologyStaminaSuper SpeedSuper StrengthAgilityEnhanced SightJumpStealthToxin and Disease ResistanceInvulnerability', 158);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Original Cindy', 'Cynthia McEachin', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/cynthia-mceachin-8090959447278309057.jpg', 'Intelligence', 6);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'In-Betweener', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/in-betweener--5917020103683259173.jpg', 'Absolute ConditionAbsorptionAccelerated HealingAge ManipulationAgilityAntimatter ManipulationAstral ProjectionBanishBiokinesisBullet TimeClairvoyanceCold ResistanceCosmic AwarenessCurse ResistanceDeath ManipulationDimensional AwarenessDuplicationDurabilityElectricity ResistanceElement ControlEnduranceEnergy BlastsEnergy ConstructsEnergy ManipulationEnergy ResistanceEnhanced ConditionEnhanced SensesEnhanced SightExtrasensory PerceptionFire ResistanceFlightHeat GenerationHeat ResistanceHellfire ResistanceIlluminationIndomitable WillInformation AnalysisIntangibilityIntelligenceInterstellar TravelInvulnerabilityJumpLatent AbilitiesLevitationLife ManipulationMagic ResistanceMarksmanshipMatter ManipulationMind ControlMind Control ResistanceMolecular ManipulationNon-Physical InteractionOmnilingualismPetrificationPhasingPortal CreationPossession ResistanceProjectionRadiation ImmunityReality WarpingReflexesResurrectionSelf-SustenanceSize ChangingSoul ManipulationSpatial AwarenessSpatial CommunicationStaminaSubatomic ManipulationSummoningSuper SpeedSuper StrengthTelekinesisTelepathy ResistanceTeleportationTerrakinesisToxin and Disease ResistanceTransmutationUnderwater breathingVision - MicroscopicVision - NightVision - TelescopicVision - ThermalVision - X-RayVoid ManipulationVortex CreationWeather ControlAcausalityAccelerated DevelopmentAcrobaticsAir ControlAnimationAnti-GravityAttack NegationAttack ReflectionAuraAvatar CreationBlack Hole ManipulationBody PuppetryCausality ManipulationCausality ResistanceClairvoyance ResistanceConceptual ManipulationCorruption ResistanceCreationCurse ManipulationDamage TransferalDarkforce ManipulationDeconstructionDexterityDimensional TravelDream ManipulationDurability NegationEmpathyEnergy AbsorptionEnergy BeamsExistence Erasure ResistanceExplosion ManipulationFire ControlGravity ControlHigher Dimensional ManipulationHyperkinesisHypnokinesisIllusion ResistanceImmortalityInvisibilityLarge SizeLaw ManipulationMagicMagic AbsorptionNon-CorporealPerception ManipulationPocket DimensionsPower Absorption ImmunityPower ModificationPsionic PowersPsychometryPurificationQuantum ManipulationReality Warping ResistanceRegenerationSense ManipulationShapeshiftingSoul ResistanceSpatial ManipulationStealthTelepathyTime Manipulation ResistanceTransformationVaporising BeamsVitakinesisWeapons MasterWind ControlWishingAdaptationChaos ManipulationExistence ErasureMaster TacticianOmnikinesisPhysics ManipulationPower AugmentationPower BestowalReactive Power LevelStatistics AmplificationWater Control', 101000000);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Ultimate Dragonoid', 'Dragonoid', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/dragonoid--2414928600611141888.jpg', 'Bullet TimeCold ResistanceDurabilityEnduranceEnergy AbsorptionEnergy BeamsEnergy BlastsEnergy ConstructsEnergy EmbodimentEnergy ManipulationEnergy ResistanceEnhanced HearingEnhanced MemoryEnhanced SensesEnhanced SightEnhanced SmellEnhanced ThieveryEnhanced TouchFire ControlFire ResistanceFlightHealHeat GenerationHeat ResistanceHellfire ManipulationHellfire ResistanceImmortalityIntelligenceInvulnerabilityJumpShapeshiftingSize ChangingStaminaSuper SpeedSuper StrengthAbsorptionAccelerated HealingAgilityBerserk ModeBloodlustDexterityDimensional AwarenessElectricity ResistanceEmotional Power UpIndomitable WillInvisibilityMarksmanshipMaster Martial ArtistMaster TacticianMatter AbsorptionMatter ManipulationMind BlastMind Control ResistanceNatural ArmorNon-CorporealPower AbsorptionRadiation ImmunityReflexesRegenerationSuper BreathTelepathy ResistanceTime Manipulation ResistanceToxin and Disease ResistanceVision - MicroscopicVision - NightVision - Telescopic', 240000);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Kevin Levin', 'Kevin Ethan Levin', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/kevin-ethan-levin-5863008903588957606.jpg', 'Ability ShiftAbsorptionAccelerated DevelopmentAccelerated HealingAcrobaticsAgilityChanging ArmorCold ResistanceDexterityDurabilityElectricity AbsorptionEnduranceEnergy AbsorptionEnhanced SensesFire ResistanceHealHeat ResistanceIndomitable WillIntelligenceMarksmanshipMaster Martial ArtistMaster TacticianMatter AbsorptionNatural ArmorNatural WeaponsPeak Human ConditionPower AbsorptionPower MimicryRadiation AbsorptionRadiation ImmunityRobotic EngineeringShapeshiftingStaminaStealthSuper SpeedSuper StrengthSwordsmanshipTransformationVehicular MasteryWeapon CreationWeapon-based PowersWeapons MasterAdaptationAnimal AttributesAnimal Oriented PowersEnhanced HearingEnhanced MemoryEnhanced SightEnhanced SmellFusionInvulnerabilityJumpLatent AbilitiesLight ControlLongevityMechanical AptitudeOmnilingualismPower SuitRage PowerReflexesRegenerationStatistics AmplificationTelepathy ResistanceToxin and Disease ResistanceVision - NightDanger SenseMetal ManipulationMind Control ResistanceMolecular Manipulation', 24000);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Ditto', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/ditto-3935766009553698817.jpg', 'Ability ShiftAdaptationDensity ControlPhotographic ReflexesPower MimicryPower ModificationShapeshiftingSize ChangingTransformation', 228);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Qui-Gon Jinn', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/qui-gon-jinn--7898656626995412827.jpg', 'AcrobaticsAgilityAnimal AttributesAnimal ControlAstral ProjectionAttack ReflectionClairvoyanceCold ResistanceDanger SenseDarkforce ManipulationDeath ManipulationDurabilityElectrokinesisElement ControlEmpathyEnduranceEnergy BeamsEnergy BlastsEnergy ManipulationEnergy ResistanceForce FieldsForce GhostIllusionsInsanityIntelligenceJumpMaster Martial ArtistMaster TacticianMatter ManipulationMemory ManipulationMind ControlMind Control ResistanceNon-Physical InteractionPeak Human ConditionPower SensePower SuitPrecognitionPsionic PowersPsychometryReflexesStaminaStealthSuper SpeedSuper StrengthTechnopath/CyberpathTelekinesisTelepathyTelepathy ResistanceTerrakinesisThe ForceWater ControlWeather ControlWind ControlConceptual ManipulationEnhanced SensesHeat ResistanceLevitationLife ManipulationLongevityMolecular ManipulationToxin and Disease ResistanceWeapons MasterFire ResistanceSoul Resistance', 57000);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Xander Shakadera', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/xander-shakadera-6055452079113193370.jpg', 'AcrobaticsAgilityAuraAwakened PowerEmotional Power UpEnhanced SensesIndomitable WillIntelligenceMaster Martial ArtistPeak Human ConditionReflexesStaminaSuper SpeedSuper StrengthDamage BoostInformation AnalysisJumpPower SenseRage PowerBerserk ModeIlluminationMaster TacticianPreparation', 63);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Padma Patil', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/padma-patil-4621488681679931635.jpg', 'Energy BlastsEnergy ConstructsFire ControlForce FieldsMagicTelekinesisTeleportationAccelerated HealingPetrificationTransmutationWater ControlMind ControlMind Control ResistanceTelepathyTelepathy Resistance', 309);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Starfire', 'Koriand''r', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/koriand''r-7730237464594107978.jpg', 'Accelerated HealingAgilityBerserk ModeCold ResistanceDurabilityElectricity ResistanceEmotional Power UpEmpathyEnduranceEnergy AbsorptionEnergy BeamsEnergy BlastsEnergy ManipulationEnergy ResistanceEnhanced SensesEnhanced SightFire ControlFire ResistanceFlightIntelligenceInterstellar TravelLevitationMarksmanshipReflexesStaminaSuper SpeedSuper StrengthToxin and Disease ResistanceAstral ProjectionAttack ReflectionEnergy ArmorForce FieldsOmnilingualismWillpower InducementElectro-Magnetism ManipulationInvulnerabilityMind Control Resistance', 14000);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Clockwork', 'Chronosapien', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/chronosapien-2317474281800614878.jpg', 'Age ManipulationBullet TimeDimensional AwarenessDurabilityEnergy BlastsInorganic PhysiologyIntelligencePeak Human ConditionPostcognitionPrecognitionSelf-SustenanceSotobro EffectSuper SpeedSuper StrengthTime ManipulationTime Manipulation ResistanceTime TravelTimeframe ControlBanishClairvoyanceCold ResistanceCosmic AwarenessDanger SenseDexterityEnhanced SensesFire ResistanceIllusionsImmortalityLongevityVaporising Beams', 194000);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Shaggy', 'Shaggy Rogers', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/shaggy-rogers-4175215895499850128.jpg', 'AcrobaticsAgilityDanger SenseEnduranceIndomitable WillInstinctive ReactionReflexesStaminaDexterityGrappling/ClimbingInformation AnalysisJumpMaster Martial ArtistMultiple PersonalitiesRadar SenseToon ForceWeapon-based PowersWeapons MasterEnhanced SmellFear InducementIndestructible DigestionInvulnerabilitySocial InfluencingStealth', 52);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Buttercup', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/buttercup--5227927759390621166.jpg', 'Cold ResistanceDurabilityElectricity ResistanceEnergy BeamsEnergy BlastsEnergy ConstructsEnhanced HearingEnhanced SensesEnhanced SightEnhanced SmellFire ControlFire ResistanceFlightInterstellar TravelStaminaSuper SpeedSuper StrengthVision - HeatVision - NightVision - X-RayVortex CreationAccelerated HealingAcrobaticsAgilityDuplicationElemental TransmogrificationForce FieldsHeat GenerationHeat ResistanceInvisibilityInvulnerabilityMagicSize ChangingSonic ScreamTeleportationMaster Martial ArtistPower BestowalReality Warping ResistanceToon Force', 41000);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Green Lantern', 'Leonard Lewis', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/leonard-lewis-1973342976947996714.jpg', 'Accelerated HealingAgilityCold ResistanceDurabilityEnduranceEnergy ResistanceEnhanced SensesFire ResistanceFlightHeat ResistanceIndomitable WillIntelligenceJumpLongevityRadiation ImmunityReflexesStaminaSuper SpeedSuper StrengthTelekinesisAbsorptionAcrobaticsAuraDexterityDivinityElectricity ResistanceEnergy BeamsEnergy BlastsEnergy ConstructsEnergy ManipulationHeat GenerationIlluminationInterstellar TravelInvulnerabilityLevitationMarksmanshipPlant ControlRegenerationSelf-SustenanceTerrakinesisToxin and Disease ResistanceTransformationAdaptationAnti-GravityAttack ReflectionDeconstructionGravity ControlMaster TacticianStealth', 108000);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Tyler Lockwood', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/tyler-lockwood--6604252198465288716.jpg', 'Animal AttributesAnimal Oriented PowersDexterityEnduranceEnhanced HearingEnhanced MemoryEnhanced SensesEnhanced SightEnhanced SmellEnhanced TouchReflexesStaminaTransformationAccelerated HealingAcrobaticsBerserk ModeJumpRage PowerRegenerationStatistics Amplification', 117);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Jeong Jeong', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/jeong-jeong--4042016590258813565.jpg', 'AcrobaticsAgilityDexterityDurabilityElement ControlFire ControlIntelligenceMarksmanshipMaster Martial ArtistMaster TacticianPeak Human ConditionStaminaSuper SpeedSuper StrengthCold ResistanceEnduranceEnergy BeamsEnergy BlastsEnhanced ConditionEnhanced SensesFire ResistanceForce FieldsHeat GenerationHeat ResistanceIndomitable WillJumpLevitationReflexesStealthWeapons MasterFlight', 243);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Alfred', 'Alfred Pennyworth', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/alfred-pennyworth--3884148212555233768.jpg', 'Intelligence', 8);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Chester Phillips', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/chester-phillips--1673419772729867063.jpg', 'MarksmanshipMaster Tactician', 8);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Carapace', 'Nino Larface', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/nino-larface--133154286482735033.jpg', 'AgilityAttack NegationDurabilityEnhanced ConditionForce FieldsJumpSuper StrengthAcrobaticsAttack ReflectionDexterityEnduranceEnergy ArmorGrappling/ClimbingHackingInstinctive ReactionPressure PointsReflexesWeapon SummoningWeapons MasterProjectionZenith', 110);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Solar Macharius', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/solar-macharius--6205480415402702467.jpg', 'AgilityAuraDurabilityFlightHealIntelligenceMarksmanshipMaster TacticianMind ControlMind Control ResistancePeak Human ConditionPhotographic ReflexesPreparationProbability ManipulationReflexesSoul ManipulationSoul ResistanceStaminaSuper SpeedSuper StrengthSupernatural ConditionSwordsmanshipTelepathyTelepathy ResistanceWeapon-based PowersWeapons MasterAngel PhysiologyElectricity ResistanceEmpathyEnergy ResistanceEnhanced ConditionEnhanced SensesFate ResistanceFire ResistanceHeat ResistanceHellfire ResistanceHoly ResistanceMagic ResistanceMaster Martial ArtistRegenerationResurrectionToxin and Disease ResistanceUnholy ResistanceInstinctive ReactionJumpLarge Size', 17000);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Gordon Agrippa', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/gordon-agrippa-8255603254049394395.jpg', 'AuraChemokinesisCreationCurse ManipulationPower AugmentationPower ModificationStatistics AmplificationStatus Effect InducementToxin and Disease ControlToxin and Disease ResistanceVitakinesisAcid ManipulationCurse ResistanceEnergy ConstructsExtrasensory PerceptionHeat ResistanceMagicPower BestowalPressure PointsProjection', 980);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'X.R', 'Experimental Ranger', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/experimental-ranger-3213479248354034195.jpg', 'DurabilityHackingTechnopath/CyberpathElasticityToxin and Disease ResistanceEnergy BeamsMultiple LimbsToon Force', 57);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Power Girl', 'Kara Zor-L', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/kara-zor-l--572317341175757576.jpg', 'Accelerated HealingAgilityCold ResistanceDexterityDurabilityEnergy BeamsEnhanced HearingEnhanced MemoryEnhanced SensesEnhanced SightEnhanced SmellFire ResistanceFlightHeat ResistanceIntelligenceInvulnerabilityJumpLongevityReflexesSelf-SustenanceStaminaSuper BreathSuper SpeedSuper StrengthVision - HeatVision - MicroscopicVision - NightVision - TelescopicVision - X-RayAbsorptionAfterimage CreationAnti-GravityAuraBerserk ModeCorruption ResistanceCryokinesisEnergy AbsorptionEnergy ResistanceExtrasensory PerceptionIndomitable WillInformation AnalysisMind Control ResistanceNatural ArmorPossessionPsionic PowersRadiation ImmunityRegenerationShockwaves GenerationSoul ResistanceTelepathy ResistanceTime ManipulationTime Manipulation ResistanceToxin and Disease ResistanceVibration Manipulation', 165000);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'War Hammer Titan', 'Lara Tybur', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/lara-tybur--4569535237846382085.jpg', 'Accelerated HealingClairvoyanceCold ResistanceImmortalityRadiation ImmunityRegenerationStaminaStatistics AmplificationToxin and Disease ResistanceWeapon CreationWeapons MasterAcid ResistantsAdaptationAgilityBody PuppetryDexterityElectricity ResistanceElectrokinesisEnduranceFire ResistanceHeat ResistanceJumpLarge SizeReflexesSelf-SustenanceTransformationWeapon SummoningWeapon-based Powers', 609);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Red Hood', 'Jason Todd', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/jason-todd-5243360652620942801.jpg', 'AcrobaticsElement ControlIntelligenceMadness ManipulationMaster Martial ArtistMaster TacticianPeak Human ConditionPreparationSmoke ManipulationStealthVehicular MasteryWeapons MasterEnhanced SensesFear ManipulationHoming AttackIllusions', 107);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Kurt Baratier', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/kurt-baratier--929190938855259752.jpg', 'AcrobaticsAgilityAuraAwakened PowerEmotional Power UpEnhanced SensesIndomitable WillInformation AnalysisIntelligenceMaster TacticianPeak Human ConditionReflexesStaminaSuper SpeedSuper StrengthDamage BoostEnhanced HearingJumpPower SenseRage PowerBerserk ModeElectricity ResistanceIlluminationPreparation', 61);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Evergreen', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/evergreen--3724141908988309997.jpg', 'DanmakuEnergy BeamsFlightForce FieldsJumpLight ControlMagicPetrificationPower Nullifier', 192);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Erza Scarlet', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/erza-scarlet--5853756018084983189.jpg', 'AcrobaticsAgilityEmotional Power UpIndomitable WillJumpPain SuppressionReflexesWeapons MasterCold ResistanceDimension StorageElectricity ResistanceEnergy ResistanceFire ResistanceFlightHeat ResistanceHoly ResistanceMagic ResistancePower Nullifier', 1000);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Eric Weiss', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/eric-weiss--5540219434310352329.jpg', 'IntelligenceMarksmanshipWeapons MasterMaster Martial ArtistMaster Tactician', 21);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Primal Kyogre', 'Kyogre', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/kyogre--1851771614972262329.jpg', 'Accelerated DevelopmentAccelerated HealingAcrobaticsAdaptationAgilityAmphibious RespirationAnimal ControlApathyAttack ReflectionAudio ControlAuraAwakened PowerBullet TimeClairvoyanceCold ResistanceCorruption ResistanceCryokinesisDamage BoostDamage ReductionDanger SenseDeconstructionDexterityDimensional AwarenessDurabilityDurability NegationElectricity AbsorptionElement ControlElemental TransmogrificationEnduranceEnergy AbsorptionEnergy BeamsEnergy BlastsEnergy ResistanceEnhanced HearingEnhanced MemoryEnhanced SensesEnhanced SightEnhanced SmellExplosion ManipulationExtrasensory PerceptionFire ResistanceHeat ResistanceHoly ResistanceHoming AttackIlluminationImmortalityIndestructible DigestionIndomitable WillInsanityInstinctive ReactionIntelligenceInterstellar TravelInvulnerabilityLight ControlLongevityMagic ResistanceMind Control ResistanceNatural WeaponsOmnilingualismPain SuppressionPossession ResistancePower AugmentationPower ModificationPower NullifierPurificationReactive EvolutionReactive Power LevelReflexesRegenerationSelf-SustenanceSize ChangingSoul ResistanceSpatial AwarenessStaminaStatistics AmplificationStatistics ReductionStatus Effect InducementSub-MarinerSuper SpeedSuper StrengthTelepathy ResistanceTerrakinesisThirstokinesisToxin and Disease ResistanceTransformationTransmutationVision - CryoVision - MicroscopicVision - NightVision - TelescopicVitakinesisVortex CreationWater ControlWeapon CreationWeapons MasterWeather ControlAttack NegationBerserk ModeCreationInformation AnalysisMatter AbsorptionMolecular DissipationMolecular ManipulationReality WarpingUnderwater breathingVaporising BeamsDivinityEmotional Power UpMatter ManipulationPower AbsorptionSound ManipulationVision - InfraredVision - Thermal', 3000000);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Alea', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/alea-4860616895031102785.jpg', 'DurabilityEnduranceStaminaSuper SpeedSuper StrengthAbsorptionElectricity ResistanceEnergy AbsorptionEnergy ConstructsEnergy ManipulationEnergy ResistanceReflexesStealthWeapons Master', 84);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Deadpool', 'Wade Wilson', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/wade-wilson--9081207994996863123.jpg', 'Accelerated HealingAcrobaticsAgilityDimensional AwarenessDurabilityEnhanced ConditionImmortalityInsanityIntelligenceLongevityMarksmanshipMaster Martial ArtistPeak Human ConditionReflexesRegenerationStaminaSuper SpeedSuper StrengthThe Fourth WallToxin and Disease ResistanceWeapon-based PowersWeapons MasterAccelerated DevelopmentAdaptationCold ResistanceDanger SenseDexterityEnduranceEnhanced HearingEnhanced SensesEnhanced SightEnhanced SmellEnhanced ThieveryExtrasensory PerceptionFire ResistanceHeat ResistanceHunters InstinctIndomitable WillJumpMaster TacticianMind Control ResistancePossession ResistancePressure PointsRadiation ImmunitySoul ResistanceStealthTelepathy ResistanceVision - NightDimension StorageInvulnerabilityTeleportation', 800);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Miles Morales', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/miles-morales-3913216445376841795.jpg', 'AgilityAnimal Oriented PowersReflexesSuper SpeedSuper StrengthWallcrawlingAnimal AttributesInvisibilityWeb CreationAccelerated HealingBerserk ModeElectrokinesisJump', 70);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Miclas (Capsule Monster)', 'Miclas', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/miclas--6353593268146846713.jpg', 'Fire ResistanceHeat ResistanceJumpLarge SizeLongevityNatural ArmorAnimal AttributesEnduranceEnergy BeamsEnergy ResistanceEnhanced SensesRadiation ImmunityAgilityNatural WeaponsSize ChangingToxin and Disease Resistance', 815);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Gogeta', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/gogeta-8543534713597214965.jpg', 'Ability ShiftAbsorptionAccelerated DevelopmentAccelerated HealingAcrobaticsAfterimage CreationAgilityAuraBerserk ModeChi ManipulationClairvoyanceCosmic AwarenessDanmakuDexterityDivinityDurabilityEmotional Power UpEnduranceEnergy AbsorptionEnergy BeamsEnergy BlastsEnergy ConstructsEnergy ManipulationEnergy ResistanceEnhanced HearingEnhanced SensesEnhanced SightEnhanced SmellFire ResistanceFlightGodly PhysiologyHealHeat GenerationHeat ResistanceIllusionsImmortalityIndomitable WillInstinctive ReactionInterstellar TravelInvulnerabilityJumpLatent AbilitiesLight ControlLongevityMarksmanshipMaster Martial ArtistMaster TacticianPeak Human ConditionPower AugmentationPower SenseRadiation AbsorptionRadiation ImmunityRage PowerReactive Power LevelReflexesStaminaStatistics AmplificationStealthSuper SpeedSuper StrengthTelepathyTeleportationVitakinesisWeapons MasterWeather ControlWind ControlAwakened PowerDimensional AwarenessGlidingReactive Evolution', 1000000);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Magetta', 'Otta Magetta', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/otta-magetta--7716939715181788894.jpg', 'Cold ResistanceDexterityDurabilityEnduranceEnergy ResistanceEnhanced ConditionFire ControlFire ResistanceHeat GenerationHeat ResistanceInvulnerabilityJumpNatural ArmorPeak Human ConditionReflexesStaminaSuper SpeedSuper StrengthAccelerated DevelopmentAccelerated HealingAcrobaticsAgilityLarge SizeLongevityMarksmanshipMaster Martial ArtistMaster TacticianRadiation ImmunityWeapon CreationAir ControlLava ManipulationWeapons MasterWind Control', 17000);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Doctor Nefario', 'Joseph Alfred Nefario', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/joseph-alfred-nefario--7205172358612565312.jpg', 'IntelligenceRobotic EngineeringVehicular MasteryWeapon-based PowersWeapons MasterGadget UsagePreparationBerserk ModeHeat ResistanceLongevityMaster Tactician', 21);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Odin', 'Odin Borson', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/odin-borson-52998479897445084.jpg', 'DurabilityElectrokinesisEnduranceIndomitable WillIntelligenceLongevityMarksmanshipReflexesStaminaStealthSuper SpeedSuper StrengthWeapons MasterAccelerated HealingAgilityAuraBanishClairvoyanceCold ResistanceDanger SenseDimensional TravelElectricity ResistanceElement ControlEnergy BeamsEnergy BlastsEnergy ResistanceEnhanced SensesEnhanced SightFire ResistanceGodly PhysiologyHeat GenerationHeat ResistanceIlluminationInterstellar TravelInvulnerabilityJumpMagicMaster Martial ArtistMaster TacticianMind Control ResistancePower AugmentationPower BestowalRadiation ImmunityRegenerationSelf-SustenanceSummoningToxin and Disease ResistanceWeapon-based PowersWeather ControlWind ControlAcrobaticsBiokinesisCreationCurse ManipulationDexterityOmnilingualismPower SenseTerrakinesisToxin and Disease ControlVaporising Beams', 13000);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Colin Creevey', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/colin-creevey-8396873013589067000.jpg', 'Force FieldsMagicPetrificationTelekinesisTeleportationEnergy BlastsEnergy ConstructsFire ControlWater ControlAccelerated HealingMind ControlTelepathyTelepathy Resistance', 218);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Alucard', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/alucard-2253589722192301503.jpg', 'Absolute ConditionAccelerated HealingAcrobaticsAgilityBerserk ModeDamage BoostDexterityDurabilityEnhanced ConditionEnhanced HearingEnhanced MemoryEnhanced SensesEnhanced SightHealInstinctive ReactionIntelligenceJumpMaster Martial ArtistMaster TacticianPeak Human ConditionReflexesStaminaStatistics AmplificationSuper SpeedSuper StrengthSwordsmanshipWeapon-based PowersAcid ResistantsAdaptationAwakened PowerBlessedBlood ManipulationCold ResistanceCurse ResistanceDurability NegationElectricity ResistanceEnergy ResistanceFire ResistanceHeat ResistanceIllusion ResistanceIntuitive aptitudeInvulnerabilityPain ManipulationRage PowerRegenerationResurrectionToxin and Disease Resistance', 1000);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Hyssop', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/hyssop-5321388219387824127.jpg', 'Cold ResistanceCryokinesisDurabilityEnduranceHealJumpPeak Human ConditionStaminaSuper SpeedSuper StrengthAbility ShiftAccelerated DevelopmentAccelerated HealingEnhanced SensesInvulnerabilityLongevityMarksmanshipMaster Martial ArtistSuper BreathWeapon CreationWeapon-based Powers', 5000);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Zatanna', 'Zatanna Zatara', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/zatanna-zatara-33652115924995789.jpg', 'AbsorptionAgilityArcane MagicAstral ProjectionAttack ReflectionCold ResistanceCryokinesisDark ArtsDensity ControlDimension StorageDimensional TravelDurabilityDurability NegationElectricity ResistanceElectrokinesisElement ControlEnergy AbsorptionEnergy BlastsEnergy ConstructsEnergy ManipulationEnergy ResistanceFire ControlFire ResistanceFlightForce FieldsGravity ControlHypnokinesisIlluminationIllusionsIntelligenceLevitationLight ControlMagicMatter ManipulationMemory ManipulationMind ControlMind Control ResistanceNon-Physical InteractionPeak Human ConditionPetrificationPhasingPossession ResistancePrecognitionReflexesShadow ManipulationSize ChangingSleep ManipulationStaminaStealthSummoningTelekinesisTelepathyTelepathy ResistanceTeleportationTransmutationWater ControlWeather ControlWind ControlAdaptationAnimationAwakened PowerBanishCloakingDexterityEnduranceEnergy ArmorEnhanced HearingEnhanced MemoryEnhanced SightEnhanced SmellExorcismHeat GenerationIndomitable WillInvisibilityMagic ResistanceMolecular ManipulationNecromancyParalysisPlant ControlPostcognitionProjectionReality WarpingSealingSoul ManipulationTime ManipulationTime Manipulation ResistanceTimeframe ControlToxin and Disease ResistanceUmbrakinesisAccelerated HealingProbability ManipulationReality Warping ResistanceSoul ResistanceTime TravelToxin and Disease Control', 1000000);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Caleb', 'Caleb Quinn', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/caleb-quinn-8090852987523057785.jpg', 'DurabilityIntelligenceMadness ManipulationStaminaSuper SpeedSuper StrengthAbsorptionAccelerated HealingAcrobaticsAgilityAttack ReflectionChain ManipulationClairvoyanceCold ResistanceDamage BoostDamage ReductionDeath ManipulationDexterityDurability NegationElectricity ResistanceElectrokinesisEnduranceEnergy BlastsEnergy ManipulationEnhanced SensesEnhanced SightExplosion ManipulationFire ControlFire ResistanceForce FieldsHeat ResistanceHoming AttackImmortalityInvisibilityInvulnerabilityJumpLongevityMagic ResistanceMarksmanshipNon-Physical InteractionPortal CreationPossessionPossession ResistancePower AbsorptionPower NullifierRage PowerReflexesRegenerationResurrectionSoul ManipulationStatistics AmplificationStealthToxin and Disease ResistanceUnderwater breathingWeapon-based PowersWeapons MasterMagicMatter ManipulationNon-CorporealReality Warping', 125000);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Rorschach II', 'Reggie', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/reggie--6928929536818000012.jpg', 'Peak Human ConditionStaminaAgilityEnduranceStealthAcrobaticsInsanityMarksmanshipReflexesWeapons Master', 35);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Mecha Team Leader', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/mecha-team-leader-8761561228355127099.jpg', 'Cold ResistanceIndomitable WillInvulnerabilitySuper SpeedSuper StrengthToxin and Disease ResistanceAdaptationAnimal AttributesDanmakuEnergy AbsorptionEnergy BeamsEnergy BlastsFire ResistanceFlightHeat ResistanceMind Control ResistancePhasingSpace SurvivabilityAgilityIlluminationSpaceflight', 3000);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Yato', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/yato--4733471052252954441.jpg', 'AcrobaticsAgilityMaster Martial ArtistReflexesRegenerationWeapons MasterEmpathyEnhanced SensesExtrasensory PerceptionForce FieldsInvisibilityJumpMemory ManipulationMind ControlNon-Physical InteractionPossessionSoul ManipulationSoul ResistanceTeleportationTransformationWeapon CreationMagic', 394);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Rogue', 'Anna Marie', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/anna-marie-8232205014591818998.jpg', 'AgilityDurabilityEnhanced MemoryEnhanced SensesEnhanced TouchFlightIndomitable WillIntelligenceMaster Martial ArtistMemory ManipulationPeak Human ConditionPower AbsorptionPower MimicryReflexesStaminaSuper SpeedSuper StrengthAccelerated HealingBerserk ModeCold ResistanceDanger SenseDexterityEnduranceEnergy ResistanceEnhanced HearingEnhanced SightFire ResistanceHeat ResistanceJumpLevitationLongevityRadiation ImmunityStatistics AmplificationStealth', 9000);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Superman', 'Kal-El', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/kal-el-8532493211384565385.jpg', 'DurabilityEnduranceEnergy BeamsFlightInvulnerabilitySuper BreathSuper SpeedSuper StrengthVision - HeatCold ResistanceCryokinesisElectricity ResistanceEnhanced HearingEnhanced SensesEnhanced SightFire ResistanceHeat ResistanceVision - InfraredVision - TelescopicVision - X-Ray', 5000);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Xuppu', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/xuppu-969679586211482788.jpg', 'AcrobaticsDivinityPower BestowalPower NullifierZenithAgilityCurse ManipulationEmpathyEnduranceEnergy AbsorptionFlight', 270);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Eijiro Kirishima', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/eijiro-kirishima-1670210196655066018.jpg', 'DurabilityNatural ArmorPeak Human ConditionFire ResistanceHeat ResistanceMaster Martial ArtistReflexes', 58);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Lightning Lad', 'Garth Ranzz', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/garth-ranzz-7867619256462428858.jpg', 'Electricity AbsorptionElectricity ResistanceElectrokinesisEnergy BlastsFlight', 165);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Sunny', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/sunny-3842023509049101430.jpg', 'AgilityAnimal AttributesFire ResistanceFlightHeat ResistanceDexterityNatural ArmorNatural Weapons', 44);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Black Panther', 'T''Challa', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/t''challa-3247215188070515269.jpg', 'DurabilityIntelligenceMarksmanshipMaster Martial ArtistMaster TacticianPeak Human ConditionReflexesStaminaStealthSuper SpeedSuper StrengthWeapons MasterAccelerated HealingAcrobaticsAgilityCamouflageCloakingDexterityEnduranceEnergy AbsorptionEnhanced HearingEnhanced SensesEnhanced SightEnhanced SmellEnhanced TouchForce FieldsHeat ResistanceIndomitable WillPower SuitVision - NightVision - TelescopicWallcrawlingEnergy Resistance', 173);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Iron', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/iron-3347644248832034591.jpg', 'DurabilityIntelligenceStaminaSuper StrengthAgilityDensity ControlElasticityFire ResistanceHeat ResistanceIntangibilityShapeshifting', 183);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Cornelius', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/cornelius-344210290884561415.jpg', 'DurabilityEnduranceEnhanced ConditionIndomitable WillIntelligencePeak Human ConditionStaminaSupernatural ConditionAccelerated DevelopmentBullet TimeCold ResistanceCorruption ResistanceElectricity ResistanceFire ResistanceHeat ResistanceInvulnerabilityLatent AbilitiesLevitationLight ControlMagicMagic ResistanceTelekinesisTerrakinesisWeapon-based PowersCurse ManipulationCurse ResistanceEnergy BlastsEnhanced MemoryMemory ManipulationMind BlastStatistics Reduction', 631);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Goku', 'Kakarot', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/kakarot--1455795604287044439.jpg', 'AbsorptionAccelerated DevelopmentAccelerated HealingAcrobaticsAdaptationAfterimage CreationAgilityApathyAuraAwakened PowerBerserk ModeChi ManipulationClairvoyanceCold ResistanceCosmic AwarenessDanger SenseDanmakuDexterityDimensional AwarenessDivinityDurabilityElectricity ResistanceEmotional Power UpEnduranceEnergy AbsorptionEnergy BeamsEnergy BlastsEnergy ConstructsEnergy ManipulationEnergy ResistanceEnhanced HearingEnhanced SensesEnhanced SightEnhanced SmellExtrasensory PerceptionFire ResistanceFlightGlidingGodly PhysiologyHealHeat GenerationHeat ResistanceHoming AttackImmortalityIndomitable WillInstinctive ReactionInterstellar TravelInvulnerabilityJumpLatent AbilitiesLongevityMarksmanshipMaster Martial ArtistMaster TacticianPeak Human ConditionPhotographic ReflexesPower SenseRadar SenseRadiation AbsorptionRadiation ImmunityRage PowerReactive EvolutionReactive Power LevelReflexesSealingSeismic PowerSocial InfluencingStaminaStatistics AmplificationStealthSuper SpeedSuper StrengthTelepathyTeleportationWeapons MasterWeather ControlAbility ShiftAttack ReflectionDimensional TravelFusionIlluminationLevitationMind Control ResistanceNon-Physical InteractionParalysisPressure PointsRegenerationSpatial AwarenessTransformationVision - NightEmpathyExplosion Manipulation', 769000);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Raphael', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/raphael-4944217910032483761.jpg', 'Animal AttributesAnimal Oriented PowersDurabilityReflexesStaminaStealthSuper SpeedSuper StrengthAccelerated HealingAcrobaticsAdaptationAgilityDexterityJumpLongevityMarksmanshipMaster Martial ArtistNatural ArmorSub-MarinerWeapons MasterBerserk ModeInvulnerability', 88);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Mace Windu', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/mace-windu--1067970804023210377.jpg', 'AbsorptionAcrobaticsAgilityChi ManipulationClairvoyanceCloakingDanger SenseDeath ManipulationDurabilityElectricity AbsorptionEmpathyEnergy AbsorptionEnergy BeamsEnhanced SensesFear InducementForce FieldsForce GhostForce SpeedHealIllusionsIndomitable WillJumpLevitationLife ManipulationMarksmanshipMaster Martial ArtistMaster TacticianMatter ManipulationMemory ManipulationMind ControlMind Control ResistanceMolecular ManipulationNon-Physical InteractionPeak Human ConditionPower SensePower SuitPrecognitionPsionic PowersPsychometryRage PowerSeismic PowerSocial InfluencingSpatial AwarenessStaminaStealthSuper SpeedSuper StrengthTelekinesisTelepathyTelepathy ResistanceTerrakinesisThe ForceVitakinesisWater ControlWeapons MasterAdaptationAnimal ControlBullet TimeCold ResistanceDarkforce ManipulationElectricity ResistanceElement ControlEnduranceFear ManipulationFire ResistanceHeat ResistanceInformation AnalysisTechnopath/CyberpathToxin and Disease ResistanceWeather ControlAstral ProjectionElectrokinesisNecromancyPower Mimicry ImmunityWind Control', 163000);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Incineroar', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/incineroar--8463735221469819453.jpg', 'Animal AttributesDamage BoostDurabilityHeat GenerationHeat ResistanceRage PowerReflexesStaminaStatistics AmplificationStatus Effect InducementAbility ShiftAccelerated HealingAgilityAnimal Oriented PowersBerserk ModeBloodlustCurse ResistanceDamage ReductionDanmakuDexterityEmotional Power UpEnhanced SensesFear InducementFear ManipulationFire ControlFire ResistanceInvulnerabilityJaw StrengthJumpMaster Martial ArtistMind Control ResistanceStatistics ReductionTelepathy ResistanceAcrobaticsCold ResistanceCurse ManipulationElectrokinesisEnhanced HearingEnhanced SightMagic ResistanceMarksmanshipMetal ManipulationOmnilingualismSand ManipulationTerrakinesis', 802);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Morbius', 'Michael Morbius', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/michael-morbius--351259523213737635.jpg', 'AcrobaticsCold ResistanceDexterityDurabilityEnduranceEnhanced HearingEnhanced MemoryEnhanced SensesEnhanced SightEnhanced SmellEnhanced TouchFear InducementFear ManipulationIntelligenceRadiation ImmunityReflexesStaminaStealthSuper SpeedSuper StrengthSurface ScalingToxin and Disease ResistanceTransformationAccelerated HealingAgilityEcholocationElasticityFlightGlidingHeat ResistanceHypnokinesisImmortalityInvulnerabilityJumpLevitationMemory ManipulationMind ControlNatural WeaponsParalysisPower NullifierRegenerationSelf-SustenanceStatistics ReductionVision - MicroscopicVision - NightVision - TelescopicWallcrawlingShapeshifting', 556);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Zatanna', 'Zatanna Zatara', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/zatanna-zatara--2179741900901759341.jpg', 'AgilityAstral ProjectionAttack NegationBanishClairvoyanceCloth ManipulationCryokinesisDark ArtsDimensional TravelDurabilityElectrokinesisElement ControlEnduranceEnergy BlastsEnergy ConstructsEnergy ManipulationEnhanced SensesExorcismFire ControlForce FieldsHeat GenerationIlluminationIntelligenceInvisibilityLatent AbilitiesLevitationMagicMarksmanshipMemory ManipulationMind Control ResistanceNon-Physical InteractionPetrificationPortal CreationPsionic PowersPsychometryReflexesSealingSense ManipulationStaminaStealthSummoningSuper SpeedSuper StrengthTelekinesisTeleportationTransformationVaporising BeamsVitakinesisVortex CreationWater ControlWind ControlAccelerated HealingAdaptationAnimationAstral TrapAttack ReflectionCold ResistanceCorruption ResistanceCurse ManipulationCurse ResistanceDanger SenseDeath ManipulationDeconstructionDexterityDurability NegationElectrical TransportElectricity ResistanceEnergy BeamsEnergy ResistanceEnhanced ThieveryExplosion ManipulationExtrasensory PerceptionFire ResistanceFlightGravity ControlHeat ResistanceHoming AttackIllusion ResistanceIllusionsIndomitable WillInformation AnalysisInvulnerabilityLaw ManipulationMagic AbsorptionMagic ResistanceMaster TacticianMorality ManipulationOrganic ManipulationPlant ControlPostcognitionPower AugmentationPower ModificationPower NullifierPrecognitionProbability ManipulationProjectionReality WarpingRegenerationResurrectionShockwaves GenerationSoul ManipulationSoul ResistanceTelepathyTelepathy ResistanceTerrakinesisTime ManipulationToxin and Disease ResistanceTransmutationVibration ManipulationWishingAcrobaticsCreationSpatial ManipulationTime Manipulation Resistance', 1000000);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Emma Frost', 'Emma Grace Frost', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/emma-grace-frost-1527955070964680734.jpg', 'DurabilityStaminaAccelerated HealingAcrobaticsAgilityEnhanced ConditionHeat ResistanceIllusionsMind ControlMind Control ResistanceNatural ArmorStealthTransmutation', 115);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Martian Manhunter', 'J''onn J''onzz', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/j''onn-j''onzz-9045437802965257570.jpg', 'AgilityDisguise MasteryDurabilityEnergy ManipulationEnhanced HearingEnhanced SightExtrasensory PerceptionFlightIllusionsInvisibilityLongevityMaster Martial ArtistMind ControlPhasingPossessionReflexesRegenerationShapeshiftingSize ChangingSuper SpeedSuper StrengthTelekinesisTelepathyVision - HeatVision - InfraredVision - MicroscopicVision - TelescopicVision - X-RayElement ControlInvulnerability', 8000);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Answer', 'Aaron Nicholoson', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/aaron-nicholoson--7231636597941386323.jpg', 'DurabilityEnhanced SensesSuper SpeedSuper StrengthDanger SenseDurability NegationFlightEnhanced ThieveryPower SenseRadar Sense', 28);
INSERT INTO hero(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Techadon Robot', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-supes/characterdata/images/techadon-robot-313680108898239037.jpg', 'DexterityDurabilityElectricity ResistanceEnduranceFire ResistanceHeat ResistanceIndomitable WillNanotechnologyNatural ArmorNatural WeaponsPeak Human ConditionPower SuitRadiation ImmunityReflexesRegenerationStaminaSuper SpeedSuper StrengthAccelerated DevelopmentAcrobaticsAdaptationAgilityEnergy BeamsEnergy BlastsInformation AnalysisInvulnerabilityJumpLongevityMarksmanshipMaster Martial ArtistVaporising BeamsWeapon-based PowersWeapons MasterLarge Size', 3000);
