---
apiVersion: v2
name: super-heroes
description: Quarkus Super Heroes - Full system umbrella chart
version: "1.0.0"
dependencies:
  - name: grpc-locations
    version: "*"
    repository: "file://../../../grpc-locations/deploy/helm/kubernetes"
  - name: rest-narration
    version: "*"
    repository: "file://../../../rest-narration/deploy/helm/kubernetes"
  - name: rest-villains
    version: "*"
    repository: "file://../../../rest-villains/deploy/helm/kubernetes"
  - name: rest-heroes
    version: "*"
    repository: "file://../../../rest-heroes/deploy/helm/kubernetes"
  - name: rest-fights
    version: "*"
    repository: "file://../../../rest-fights/deploy/helm/kubernetes"
  - name: event-statistics
    version: "*"
    repository: "file://../../../event-statistics/deploy/helm/kubernetes"
  - name: ui-super-heroes
    version: "*"
    repository: "file://../../../ui-super-heroes/deploy/helm/kubernetes"
