---
apiVersion: v1
kind: Service
metadata:
  name: otel-lgtm
  labels:
    name: otel-lgtm
    system: quarkus-super-heroes
    app: otel-lgtm
    role: monitoring
spec:
  ports:
    - port: 3000
      name: grafana
      protocol: TCP
      targetPort: 3000
    - port: 4317
      name: otlp-grpc
      protocol: TCP
      targetPort: 4317
    - port: 4318
      name: otlp-http
      protocol: TCP
      targetPort: 4318
  selector:
    name: otel-lgtm
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/name: otel-lgtm
    app.kubernetes.io/part-of: monitoring
    system: quarkus-super-heroes
    name: otel-lgtm
    app: otel-lgtm
    role: monitoring
  name: grafana
spec:
  port:
    targetPort: 3000
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: otel-lgtm
