---
app:
  envs:
    QUARKUS_OTEL_K8S_RESOURCE_CONTAINER_NAME: rest-heroes
    QUARKUS_OTEL_K8S_RESOURCE_DEPLOYMENT_NAME: rest-heroes
  image: quay.io/quarkus-super-heroes/rest-heroes:native-latest
  livenessProbe:
    failureThreshold: 3
    httpGet:
      path: /q/health/live
      scheme: HTTP
    initialDelaySeconds: 5
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 10
  ports:
    http: 8083
    http1: 8083
  readinessProbe:
    failureThreshold: 3
    httpGet:
      path: /q/health/ready
      scheme: HTTP
    initialDelaySeconds: 5
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 10
