/**
 * Fight API
 * This API allows a hero and a villain to fight
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Hero } from './hero';
import { Villain } from './villain';


/**
 * A fight between one hero and one villain
 */
export class Fighters {
  constructor(
    public hero?: Hero,
    public villain?: Villain,
  ) {
  }
}
