CREATE ROLE super WITH LOGIN PASSWORD 'super';

CREATE ROLE superbad WITH LOGIN PASSWORD 'superbad' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
CREATE DATABASE villains_database;
GRANT ALL PRIVILEGES ON DATABASE villains_database TO superbad;
GRANT ALL PRIVILEGES ON DATABASE villains_database TO super;
