---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: locations-db
    application: locations-service
    system: quarkus-super-heroes
    app.kubernetes.io/part-of: locations-service
    app.openshift.io/runtime: mariadb
  name: locations-db
spec:
  replicas: 1
  selector:
    matchLabels:
      name: locations-db
  template:
    metadata:
      annotations:
        alpha.image.policy.openshift.io/resolve-names: '*'
      labels:
        application: locations-service
        name: locations-db
    spec:
      containers:
        - env:
            - name: MARIADB_SKIP_TEST_DB
              value: "true"
          envFrom:
            - secretRef:
                name: locations-db-config
          image: mariadb:12-ubi10
          name: locations-db
          ports:
            - containerPort: 3306
          resources:
            limits:
              memory: 256Mi
            requests:
              memory: 64Mi
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: locations-db-data
            - mountPath: /run/mariadb
              name: locations-db-run
            - mountPath: /docker-entrypoint-initdb.d
              name: locations-initdata
      initContainers:
        - command:
            - sh
            - get-data.sh
          image: registry.access.redhat.com/ubi8-minimal:8.6
          name: get-data
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d
              name: locations-initdata
            - mountPath: /tmp/dbinit
              name: locations-db-init
          workingDir: /tmp/dbinit
      volumes:
        - emptyDir: {}
          name: locations-db-data
        - emptyDir: {}
          name: locations-db-run
        - emptyDir: {}
          name: locations-initdata
        - configMap:
            name: locations-db-init
          name: locations-db-init
