package io.quarkus.sample.superheroes.narration.rest;

final class Examples {
  private Examples() {

  }

	static final String EXAMPLE_FIGHT = """
    {
      "winnerName": "Chewbacca",
      "winnerLevel": 5,
      "winnerPicture": "https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/chewbacca--684239239428094811.jpg",
      "winnerPowers": "Big, hairy, strong",
      "winnerTeam": "heroes",
      "loserName": "Wanderer",
      "loserLevel": 3,
      "loserPicture": "https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/wanderer-300775911119209178.jpg",
      "loserPowers": "Not strong",
      "location": {
        "name": "Gotham City",
        "description": "An American city rife with corruption and crime, the home of its iconic protector Batman."
      }
    }
		""";

  static final String EXAMPLE_FIGHT_IMAGE = """
    {
      "imageUrl": "https://somewhere.com/someimage.png",
      "imageNarration": "This is an alternate narration generated by the model based on the original narration"
    }
    """;
}
