---
app:
  envs:
    OPENAI_API_KEY: change-me
    QUARKUS_OTEL_K8S_RESOURCE_CONTAINER_NAME: rest-narration
    QUARKUS_OTEL_K8S_RESOURCE_DEPLOYMENT_NAME: rest-narration
    quarkus:
      wiremock:
        devservices:
          port: ""
  image: quay.io/quarkus-super-heroes/rest-narration:java21-latest
  livenessProbe:
    failureThreshold: 3
    httpGet:
      path: /q/health/live
      scheme: HTTP
    initialDelaySeconds: 5
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 10
  ports:
    http: 8087
    http1: 8087
  readinessProbe:
    failureThreshold: 3
    httpGet:
      path: /q/health/ready
      scheme: HTTP
    initialDelaySeconds: 5
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 10
