#!/bin/bash -ex

# Create the deploy/k8s and deploy/helm files for each java version of each of the Quarkus services
# Then add on the ui-super-heroes, monitoring, and umbrella helm charts

INPUT_DIR=src/main/kubernetes
K8S_OUTPUT_DIR=deploy/k8s
HELM_OUTPUT_DIR=deploy/helm
DEPLOYMENT_TYPES=("kubernetes" "minikube" "openshift" "knative")
MONITORING_DEPLOYMENT_TYPES=("kubernetes" "minikube" "openshift")
JAVA_VERSIONS=(25)
PROJECTS=("grpc-locations" "rest-narration" "rest-villains" "rest-heroes" "rest-fights" "event-statistics" "ui-super-heroes")
DOWNSTREAM_PROJECTS=("rest-villains" "rest-heroes" "rest-narration" "grpc-locations")

create_output_file() {
  local output_file=$1

  if [[ ! -f "$output_file" ]]; then
    echo "Creating output file: $output_file"
    touch "$output_file"

    # This is here because of
    # https://github.com/quarkusio/quarkus-super-heroes/issues/299
    echo '#######################################################################' >> $output_file
    echo '# THIS FILE IS AUTOMATICALLY GENERATED DURING CI/CD.' >> $output_file
    echo '# ANY LOCAL CHANGES YOU MAKE SHOULD NOT BE COMMITTED TO SOURCE CONTROL.' >> $output_file
    echo '#######################################################################' >> $output_file
    echo '' >> "$output_file"
  fi
}

split_yaml_by_kind() {
  local outdir="$1"
  shift

  for source_file in "$@"; do
    if [[ -f "$source_file" ]]; then
      (cd "$outdir" && yq eval-all --split-exp '(.kind | downcase)' "$OLDPWD/$source_file")

      for f in "$outdir"/*.yml; do
        [[ -f "$f" ]] && mv "$f" "${f%.yml}.yaml"
      done
    fi
  done
}

do_build() {
  local project=$1
  local version_tag=$2
  local javaVersion=$3
  local kind=$4
  local container_tag="${version_tag}-latest"
  local git_server_url="${GITHUB_SERVER_URL:=https://github.com}"
  local git_repo="${GITHUB_REPOSITORY:=quarkusio/quarkus-super-heroes}"
  local github_ref_name="${BRANCH:=${GITHUB_REF_NAME:=main}}"

  if [[ "$kind" == "native-" ]]; then
    local mem_limit="128Mi"
    local mem_request="32Mi"
  else
    local mem_limit="768Mi"
    local mem_request="256Mi"
  fi

  echo "Generating app resources for $project/$container_tag"
  rm -rf $project/target

  printf -v deployment_types_str '%s,' "${DEPLOYMENT_TYPES[@]}"

  $project/mvnw -f $project/pom.xml versions:set -DnewVersion=$container_tag -DgenerateBackupPoms=false && \
  $project/mvnw -f $project/pom.xml clean package \
    -DskipTests \
    -Dmaven.compiler.release=$javaVersion \
    -Dquarkus.liquibase-mongodb.migrate-at-start=false \
    -Dquarkus.container-image.tag=$container_tag \
    -Dquarkus.kubernetes.deployment-target=$deployment_types_str \
    -Dquarkus.kubernetes.version=$container_tag \
    -Dquarkus.kubernetes.ingress.expose=false \
    -Dquarkus.kubernetes.resources.limits.memory=$mem_limit \
    -Dquarkus.kubernetes.resources.requests.memory=$mem_request \
    -Dquarkus.kubernetes.annotations.\"app.quarkus.io/vcs-url\"=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY \
    -Dquarkus.kubernetes.annotations.\"app.quarkus.io/vcs-ref\"=$github_ref_name \
    -Dquarkus.openshift.route.expose=true \
    -Dquarkus.openshift.prometheus.generate-service-monitor=false \
    -Dquarkus.openshift.annotations.\"app.openshift.io/vcs-url\"=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY \
    -Dquarkus.openshift.annotations.\"app.openshift.io/vcs-ref\"=$github_ref_name \
    -Dquarkus.knative.labels.\"app.openshift.io/runtime\"=quarkus \
    -Dquarkus.knative.annotations.\"app.openshift.io/vcs-url\"=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY \
    -Dquarkus.knative.annotations.\"app.openshift.io/vcs-ref\"=$github_ref_name
}

process_k8s_project() {
  local project=$1
  local deployment_type=$2
  local version_tag=$3
  local javaVersion=$4
  local kind=$5
  local output_filename="${version_tag}-${deployment_type}"
  local app_generated_input_file="$project/target/kubernetes/${deployment_type}.yml"
  local project_output_file="$project/$K8S_OUTPUT_DIR/${output_filename}.yml"
  local all_apps_output_file="$K8S_OUTPUT_DIR/${output_filename}.yml"

  if [[ ! -d "$project/$K8S_OUTPUT_DIR" ]]; then
    mkdir -p $project/$K8S_OUTPUT_DIR
  fi

  create_output_file $project_output_file
  create_output_file $all_apps_output_file

  # Now merge the generated resources to the top level (deploy/k8s)
  if [[ -f "$app_generated_input_file" ]]; then
    echo "Copying app generated input ($app_generated_input_file) to $project_output_file and $all_apps_output_file"

    cat $app_generated_input_file >> $project_output_file
    cat $app_generated_input_file >> $all_apps_output_file
  fi

  if [[ "$project" == "rest-fights" ]]; then
    # Create a descriptor for all of the downstream services (rest-heroes, rest-villains, and rest-narration)
    local all_downstream_output_file="$project/$K8S_OUTPUT_DIR/${output_filename}-all-downstream.yml"
    local villains_output_file="rest-villains/$K8S_OUTPUT_DIR/${output_filename}.yml"
    local heroes_output_file="rest-heroes/$K8S_OUTPUT_DIR/${output_filename}.yml"
    local narration_output_file="rest-narration/$K8S_OUTPUT_DIR/${output_filename}.yml"
    local locations_output_file="grpc-locations/$K8S_OUTPUT_DIR/${output_filename}.yml"

    rm -rf $all_downstream_output_file

    create_output_file $all_downstream_output_file

    echo "Copying ${app_generated_input_file}, ${villains_output_file}, ${heroes_output_file}, ${narration_output_file}, and ${locations_output_file} to ${all_downstream_output_file}"
    if [[ -f "$villains_output_file" ]]; then
      cat $villains_output_file >> $all_downstream_output_file
    fi

    if [[ -f "$heroes_output_file" ]]; then
      cat $heroes_output_file >> $all_downstream_output_file
    fi

    if [[ -f "$narration_output_file" ]]; then
      cat $narration_output_file >> $all_downstream_output_file
    fi

    if [[ -f "$locations_output_file" ]]; then
      cat $locations_output_file >> $all_downstream_output_file
    fi

    if [[ -f "$app_generated_input_file" ]]; then
      cat $app_generated_input_file >> $all_downstream_output_file
    fi
  fi
}

process_helm_chart() {
  local project=$1
  local deployment_type=$2
  local version_tag=$3
  local javaVersion=$4
  local kind=$5
  local app_name=$(basename $project)
  local generated_chart_dir="$project/target/helm/${deployment_type}/${app_name}"
  local output_chart_dir="$project/$HELM_OUTPUT_DIR/${deployment_type}"

  if [[ ! -d "$generated_chart_dir" ]]; then
    echo "No Helm chart generated at $generated_chart_dir — skipping"
    return
  fi

  if [[ "$kind" == "" ]]; then
    local values_filename="values-java${javaVersion}.yaml"
  else
    local values_filename="values-native.yaml"
  fi

  if [[ "$kind" == "" ]]; then
    # First build (java) — copy entire chart directory
    echo "Copying Helm chart from $generated_chart_dir to $output_chart_dir"
    mkdir -p "$output_chart_dir"
    cp -r "$generated_chart_dir"/* "$output_chart_dir/"

    # Rename values.yaml to values-java<version>.yaml
    if [[ -f "$output_chart_dir/values.yaml" ]]; then
      mv "$output_chart_dir/values.yaml" "$output_chart_dir/$values_filename"
    fi
  else
    # Subsequent build (native) — only copy the values file
    if [[ -f "$generated_chart_dir/values.yaml" ]]; then
      echo "Copying native values from $generated_chart_dir/values.yaml to $output_chart_dir/$values_filename"
      cp "$generated_chart_dir/values.yaml" "$output_chart_dir/$values_filename"
    fi
  fi

  # Create a placeholder values.yaml so helm lint passes
  # Users must use -f values-java25.yaml or -f values-native.yaml
  if [[ ! -f "$output_chart_dir/values.yaml" ]]; then
    echo '# Use -f values-java<java-version>.yaml or -f values-native.yaml when installing this chart' > "$output_chart_dir/values.yaml"
  fi

  # For rest-fights, also create the all-downstream umbrella chart
  if [[ "$project" == "rest-fights" ]]; then
    local umbrella_dir="rest-fights/$HELM_OUTPUT_DIR/${deployment_type}-all-downstream"

    if [[ "$kind" == "" ]]; then
      echo "Creating rest-fights all-downstream umbrella chart for $deployment_type"
      mkdir -p "$umbrella_dir"

      local deps=""
      deps="${deps}
  - name: rest-fights
    version: \"*\"
    repository: \"file://../${deployment_type}\""

      for downstream in "${DOWNSTREAM_PROJECTS[@]}"
      do
        local downstream_chart_dir="$downstream/$HELM_OUTPUT_DIR/${deployment_type}"
        if [[ -d "$downstream_chart_dir" ]]; then
          deps="${deps}
  - name: ${downstream}
    version: \"*\"
    repository: \"file://../../../${downstream}/${HELM_OUTPUT_DIR}/${deployment_type}\""
        fi
      done

      cat > "$umbrella_dir/Chart.yaml" <<CHART_EOF
---
apiVersion: v2
name: super-heroes-fights
description: Quarkus Super Heroes - Fights service with all downstream dependencies
version: "1.0.0"
dependencies:${deps}
CHART_EOF
    fi

    # Generate umbrella values file for this kind
    local downstream_umbrella_values="$umbrella_dir/$values_filename"
    echo "---" > "$downstream_umbrella_values"

    # Add rest-fights values
    if [[ -f "$output_chart_dir/$values_filename" ]]; then
      yq eval '{"rest-fights": .}' "$output_chart_dir/$values_filename" >> "$downstream_umbrella_values"
    fi

    # Add each downstream project's values
    for downstream in "${DOWNSTREAM_PROJECTS[@]}"
    do
      local downstream_values="$downstream/$HELM_OUTPUT_DIR/${deployment_type}/$values_filename"
      if [[ -f "$downstream_values" ]]; then
        key="$downstream" yq eval '{ strenv(key): . }' "$downstream_values" >> "$downstream_umbrella_values"
      fi
    done
  fi
}

create_monitoring() {
  local monitoring_name="monitoring"

  echo ""
  echo "-----------------------------------------"
  echo "Creating monitoring"

  for deployment_type in "kubernetes" "minikube" "openshift"
  do
    local output_file_name="${monitoring_name}-${deployment_type}.yml"
    local output_file="$K8S_OUTPUT_DIR/$output_file_name"
    local input_dir="$monitoring_name/k8s"
    create_output_file $output_file

    if [[ -f "$input_dir/base.yml" ]]; then
      echo "Adding base config from $input_dir/base.yml into $output_file"
      cat "$input_dir/base.yml" >> $output_file
    fi

    if [[ -f "$input_dir/${deployment_type}.yml" ]]; then
      echo "Adding $deployment_type config from $input_dir/${deployment_type}.yml into $output_file"
      cat "$input_dir/${deployment_type}.yml" >> $output_file
    fi
  done

  # Helm monitoring charts — split multi-document YAMLs into per-resource template files
  for deployment_type in "${MONITORING_DEPLOYMENT_TYPES[@]}"
  do
    local monitoring_dir="$HELM_OUTPUT_DIR/monitoring-${deployment_type}"

    echo "Creating monitoring Helm chart for $deployment_type"
    mkdir -p "$monitoring_dir/templates"

    cat > "$monitoring_dir/Chart.yaml" <<CHART_EOF
---
apiVersion: v2
name: monitoring
description: Grafana LGTM monitoring stack for Quarkus Super Heroes
version: "1.0.0"
CHART_EOF

    # Split base.yml and target-specific YAML into individual template files by resource kind
    split_yaml_by_kind "$monitoring_dir/templates" "$input_dir/base.yml" "$input_dir/${deployment_type}.yml"
  done
}

create_umbrella_charts() {
  echo ""
  echo "-----------------------------------------"
  echo "Creating umbrella Helm charts"

  for deployment_type in "${DEPLOYMENT_TYPES[@]}"
  do
    local umbrella_dir="$HELM_OUTPUT_DIR/${deployment_type}"

    echo "Creating umbrella chart at $umbrella_dir"
    mkdir -p "$umbrella_dir"

    local deps=""

    for project in "${PROJECTS[@]}"
    do
      local project_chart_dir="$project/$HELM_OUTPUT_DIR/${deployment_type}"
      if [[ -d "$project_chart_dir" ]]; then
        deps="${deps}
  - name: ${project}
    version: \"*\"
    repository: \"file://../../../${project}/${HELM_OUTPUT_DIR}/${deployment_type}\""
      fi
    done

    cat > "$umbrella_dir/Chart.yaml" <<CHART_EOF
---
apiVersion: v2
name: super-heroes
description: Quarkus Super Heroes - Full system umbrella chart
version: "1.0.0"
dependencies:${deps}
CHART_EOF

    echo '# Use -f values-java<java-version>.yaml or -f values-native.yaml when installing this chart' > "$umbrella_dir/values.yaml"

    for kind in "" "native-"
    do
      for javaVersion in "${JAVA_VERSIONS[@]}"
      do
        if [[ "$kind" == "" ]]; then
          local sub_values_filename="values-java${javaVersion}.yaml"
        else
          local sub_values_filename="values-native.yaml"
        fi

        local umbrella_values_file="$umbrella_dir/$sub_values_filename"
        echo "---" > "$umbrella_values_file"

        for project in "${PROJECTS[@]}"
        do
          local project_values="$project/$HELM_OUTPUT_DIR/${deployment_type}/$sub_values_filename"
          if [[ -f "$project_values" ]]; then
            key="$project" yq eval '{ strenv(key): . }' "$project_values" >> "$umbrella_values_file"
          fi
        done
      done
    done
  done
}

create_apps() {
  for project in "${PROJECTS[@]}"
  do
    rm -rf $project/$K8S_OUTPUT_DIR/*.yml
    # Clean generated helm charts but preserve README.md
    find "$project/$HELM_OUTPUT_DIR" -mindepth 1 -maxdepth 1 -not -name README.md -exec rm -rf {} + 2>/dev/null || true

    for kind in "" "native-"
    do
      for javaVersion in "${JAVA_VERSIONS[@]}"
      do
        if [[ "$kind" == "native-" ]]; then
          version_tag="native"
        else
          version_tag="${kind}java${javaVersion}"
        fi

        # Generate all resources (k8s + helm) for all deployment types in one shot
        do_build "$project" "$version_tag" "$javaVersion" "$kind"

        for deployment_type in "${DEPLOYMENT_TYPES[@]}"
        do
          # Process k8s descriptors
          process_k8s_project "$project" "$deployment_type" "$version_tag" "$javaVersion" "$kind"

          # Process helm charts
          process_helm_chart "$project" "$deployment_type" "$version_tag" "$javaVersion" "$kind"
        done
      done
    done
  done
}

rm -rf $K8S_OUTPUT_DIR/*.yml
# Clean generated helm charts but preserve README.md
find $HELM_OUTPUT_DIR -mindepth 1 -maxdepth 1 -not -name README.md -exec rm -rf {} + 2>/dev/null || true

create_apps

## Handle monitoring (both k8s and helm)
create_monitoring

## Create top-level umbrella helm charts
create_umbrella_charts
