---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: rest-narration
    application: narration-service
    system: quarkus-super-heroes
  name: rest-narration-config
data:
  quarkus.otel.exporter.otlp.endpoint: http://otel-lgtm:4318
