@startuml
!include <logos/kafka>
!include <logos/postgresql>
!include <logos/mariadb>
!include <logos/mongodb>
!include <logos/react>
!include <logos/grafana>
!include <logos/quarkus>
!include <logos/jquery>
!include style.puml

skinparam NodePadding 40
skinparam dpi 100
skinparam backgroundColor transparent

left to right direction

together {
    node "<$grafana>" as grafana {
    }

    node "OpenTelemetry Collector" as otelCollector {
    }

    node "Super Hero UI" as ui {
      agent "<$react>" <<frontend>> as reactUi
      agent "`<$quarkus>" as uiQuarkus
      reactUi .up> uiQuarkus
    }
}

node "Fight" as fight {
    agent "<$quarkus> <<reactive>>" as fightQuarkus
    database "<$mongodb>" as fightMongoDb
    fightQuarkus .up> fightMongoDb
}

node "Narration" as narration {
  agent "<$quarkus>" <<blocking>> as narrationQuarkus
  hexagon "LangChain4j" as langchain
  narrationQuarkus .up> langchain
}

cloud "OpenAI" as openai

node "Hero" as hero {
    agent "<$quarkus>" <<reactive>> as heroQuarkus
    database "<$postgresql>" as heroPostgresql
    heroQuarkus .up> heroPostgresql
}

node "Villain" as villain {
    agent "<$quarkus>" <<blocking>> as villainQuarkus
    database "<$postgresql>" as villainPostgresql
    villainQuarkus .up> villainPostgresql
}

node "Location" as location {
		agent "<$quarkus>" <<blocking>> as locationQuarkus
		database "<$mariadb>" as locationMariadb
		locationQuarkus .up> locationMariadb
}

together {
  queue "<$kafka>" as kafka {
  }

  node "Apicurio" <<schema-registry>> as apicurio {
  }
}

'package "stats" {
    node "Event Statistics" as stat {
        agent "<$quarkus>" <<reactive>><<event-driven>> as statQuarkus
        agent "<$jquery>" <<html>> as uiStats
    }

reactUi --> fightQuarkus : HTTP
fightQuarkus --> narrationQuarkus : HTTP
fightQuarkus --> villainQuarkus : HTTP
fightQuarkus --> heroQuarkus : HTTP
fightQuarkus -[dotted]-> locationQuarkus : gRPC

langchain --> openai : HTTP

fightQuarkus ..> kafka : Message
fightQuarkus --> apicurio : HTTP

statQuarkus <.. kafka : Message
statQuarkus --> apicurio : HTTP
statQuarkus ..> uiStats : WebSocket

otelCollector .> grafana
otelCollector <-[dotted]- fightQuarkus : http/protobuf
otelCollector <-[dotted]- heroQuarkus : http/protobuf
otelCollector <-[dotted]- villainQuarkus : http/protobuf
otelCollector <-[dotted]- narrationQuarkus : http/protobuf
otelCollector <-[dotted]- statQuarkus : http/protobuf
otelCollector <-[dotted]- locationQuarkus : http/protobuf
@enduml
