---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    app.quarkus.io/vcs-ref: main
    app.openshift.io/vcs-ref: main
    app.openshift.io/connects-to: "fights-db,fights-kafka,apicurio,rest-villains,rest-heroes,rest-narration,grpc-locations,otel-lgtm"
    app.quarkus.io/vcs-url: https://github.com/quarkusio/quarkus-super-heroes
    app.openshift.io/vcs-url: https://github.com/quarkusio/quarkus-super-heroes
    app.quarkus.io/quarkus-version: 3.40.1
    app.quarkus.io/commit-id: 587ff360df4be0ad564e27c1e315b1fa8240c546
    app.quarkus.io/vcs-uri: https://github.com/quarkusio/quarkus-super-heroes.git
    app.quarkus.io/build-timestamp: 2026-10-06 - 01:52:42 +0000
  labels:
    app: rest-fights
    system: quarkus-super-heroes
    application: fights-service
    app.openshift.io/runtime: quarkus
    app.kubernetes.io/managed-by: quarkus
    app.kubernetes.io/part-of: fights-service
    app.kubernetes.io/name: rest-fights
    app.kubernetes.io/version: java25-latest
  name: rest-fights
