---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    app.quarkus.io/vcs-ref: main
    app.openshift.io/vcs-ref: main
    app.openshift.io/connects-to: "fights-db,fights-kafka,apicurio,rest-villains,rest-heroes,rest-narration,grpc-locations,otel-lgtm"
    app.quarkus.io/vcs-url: https://github.com/quarkusio/quarkus-super-heroes
    app.openshift.io/vcs-url: https://github.com/quarkusio/quarkus-super-heroes
    app.quarkus.io/quarkus-version: 3.36.3
    app.quarkus.io/vcs-uri: https://github.com/quarkusio/quarkus-super-heroes.git
    app.quarkus.io/build-timestamp: 2026-06-24 - 02:45:10 +0000
  labels:
    app: rest-fights
    system: quarkus-super-heroes
    application: fights-service
    app.openshift.io/runtime: quarkus
    app.kubernetes.io/managed-by: quarkus
    app.kubernetes.io/name: rest-fights
    app.kubernetes.io/version: java25-latest
    app.kubernetes.io/part-of: fights-service
  name: rest-fights
