---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rest-narration-config
  labels:
    app: rest-narration
    application: narration-service
    system: quarkus-super-heroes
data:
  quarkus.otel.exporter.otlp.endpoint: http://otel-lgtm:4318
