---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: grpc-locations
    application: locations-service
    system: quarkus-super-heroes
  name: grpc-locations-config-creds
data:
  quarkus.datasource.username: bG9jYXRpb25z
  quarkus.datasource.password: bG9jYXRpb25z
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: locations-db
    application: locations-service
    system: quarkus-super-heroes
  name: locations-db-config
data:
  MARIADB_DATABASE: bG9jYXRpb25zX2RhdGFiYXNl
  MARIADB_USER: bG9jYXRpb25z
  MARIADB_PASSWORD: bG9jYXRpb25z
  MARIADB_ROOT_PASSWORD: bG9jYXRpb25z
type: Opaque
