-- A 100 record random sample from https://github.com/quarkusio/quarkus-super-heroes/blob/characterdata/all-villains.sql
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Vayne', 'Shauna Vayne', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/shauna-vayne-849469911022914728.jpg', 'AcrobaticsIntelligenceMarksmanshipPower NullifierVision - NightCold ResistanceDexterityDurability NegationInvisibilityMagic ResistanceMaster Martial ArtistNon-Physical InteractionReflexesSwordsmanshipWeapon-based PowersIndomitable WillInvulnerability', 134);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Death Dealer', 'Li Ching-Lin', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/li-ching-lin-5738382045037481034.jpg', 'Master Martial ArtistReflexesWeapons MasterAgilityBerserk ModeMaster Tactician', 69);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Black Manta', 'David Milton Hyde', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/david-milton-hyde--1521761582315844505.jpg', 'AgilityDurabilityEnduranceEnhanced SensesGadget UsageIntelligenceMarksmanshipReflexesStaminaStealthSuper SpeedSuper StrengthVehicular MasteryWeapons MasterAcrobaticsElectrical TransportEnergy BeamsEnergy BlastsEnhanced SightExplosion ManipulationFire ResistanceInvulnerabilityMaster Martial ArtistMaster TacticianSwordsmanshipUnderwater breathingCold ResistanceDeath ManipulationEnergy ResistanceHeat ResistanceJumpLatent AbilitiesPetrificationSub-MarinerWeapon-based Powers', 235);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Inspector 13', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/inspector-13-1384032230840289124.jpg', 'AgilityDexterityDurabilityInformation AnalysisIntelligencePeak Human ConditionPower SuitRobotic EngineeringStaminaSuper SpeedSuper StrengthTechnopath/CyberpathAccelerated DevelopmentAcrobaticsCold ResistanceElectrokinesisEnduranceEnergy ConstructsFire ResistanceHeat ResistanceIndomitable WillInvulnerabilityJumpMarksmanshipMaster Martial ArtistMaster TacticianRadiation ImmunityReflexesRegenerationStealthTechnological PossessionWeapon CreationWeapon-based PowersWeapons Master', 219);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Orga (Millennium)', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/orga-(millennium)--5666729272259424567.jpg', 'Accelerated HealingEnhanced SensesJaw StrengthNatural ArmorNatural WeaponsRegenerationAbsorptionAnimal AttributesCold ResistanceElectricity ResistanceEnergy BlastsEnergy ResistanceEnhanced SightEnhanced SmellFire ResistanceHeat ResistanceInvulnerabilityJumpLarge SizeMechanical AptitudeRadiation AbsorptionRadiation ImmunityReactive EvolutionSummoningToxin and Disease ResistanceWeapon-based PowersHoming AttackPower AbsorptionTechnological Possession', 1000);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Myrwhydden', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/myrwhydden-4208409496371023790.jpg', 'MagicMagic Resistance', 14);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Thorfinn', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/thorfinn-7555628780161351756.jpg', 'AcrobaticsAgilityBloodlustDexterityEnhanced SensesMaster Martial ArtistMaster TacticianStaminaStealthWeapons MasterBerserk ModeEnduranceInformation AnalysisInsanityJumpPain ManipulationPain SuppressionRage PowerReflexesSwordsmanship', 73);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Parallax', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/parallax-6215289132911183104.jpg', 'AbsorptionAccelerated HealingAnimal AttributesAstral ProjectionAuraAwakened PowerBanishBerserk ModeCamouflageCold ResistanceConceptual ManipulationCorruption ResistanceCosmic AwarenessDimensional AwarenessDimensional TravelDurabilityElasticityElement ControlEmotional Power UpEmpathyEnergy AbsorptionEnergy ArmorEnergy BeamsEnergy BlastsEnergy ConstructsEnergy EmbodimentEnergy ManipulationEnergy ResistanceEnhanced HearingEnhanced MemoryEnhanced SensesEnhanced SightEnhanced SmellExistence ErasureExistence Erasure ResistanceFear InducementFear ManipulationFlightForce FieldsGodly PhysiologyIlluminationIllusionsImmortalityIntangibilityIntelligenceInvisibilityInvulnerabilityLongevityMaster TacticianMatter AbsorptionMind BlastMind ControlNon-CorporealNon-Physical InteractionPerception ManipulationPortal CreationPossessionPower AbsorptionPower BestowalPrecognitionProjectionReality WarpingRegenerationResurrectionSelf-SustenanceShapeshiftingSize ChangingSpatial AwarenessSpatial ManipulationStaminaSuper SpeedSuper StrengthTelekinesisTelepathyTelepathy ResistanceTeleportationTime ManipulationTime TravelToxin and Disease ResistanceAgilityClairvoyanceClairvoyance ResistanceDamage ReductionDanger SenseDensity ControlElectricity ResistanceFire ControlFire ResistanceHeat GenerationHeat ResistanceHoly ResistanceInterstellar TravelLarge SizeOmnilingualismPossession ResistancePower Absorption ImmunityPower AugmentationPower ModificationPower NullifierPower SenseRadiation ImmunityReality Warping ResistanceReflexesSoul ResistanceSpatial CommunicationStealthTime Manipulation ResistanceUnholy Manipulation', 76000000);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Bishop', 'Lucas Bishop', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/lucas-bishop-5392356712279195970.jpg', 'DurabilityEnergy BlastsMarksmanshipSuper SpeedSuper StrengthAbsorptionAccelerated HealingAgilityAttack NegationAttack ReflectionCold ResistanceElectricity AbsorptionEnergy AbsorptionEnergy BeamsFire ResistanceForce FieldsHeat ResistanceInvulnerabilityMaster Martial ArtistMind BlastPossession ResistancePsionic PowersReflexesRegenerationToxin and Disease ResistanceWeapon-based PowersWeapons MasterDanger SenseEnergy ManipulationMagic', 2000);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Monster (A Quiet Place)', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/monster-(a-quiet-place)-3126377054721756914.jpg', 'DurabilityEnhanced HearingEnhanced SensesPeak Human ConditionSelf-SustenanceStaminaSuper SpeedSuper StrengthAgilityAnimal AttributesAnimal Oriented PowersDanger SenseEcholocationEnduranceEnhanced SmellFire ResistanceHeat ResistanceNatural ArmorNatural WeaponsReactive EvolutionReflexesStealthJump', 42);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Vilgax', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/vilgax--6903019031807900930.jpg', 'Accelerated DevelopmentAgilityCyborgizationDurabilityEnduranceEnhanced SensesIntelligenceMarksmanshipMaster Martial ArtistMaster TacticianNatural WeaponsPeak Human ConditionReflexesStaminaSuper SpeedSuper StrengthSwordsmanshipTentaclesWeapon-based PowersWeapons MasterAccelerated HealingAcrobaticsBerserk ModeBullet TimeCold ResistanceDanger SenseDexterityDimensional TravelEnergy BeamsEnergy BlastsEnergy ResistanceEnhanced ConditionEnhanced HearingEnhanced SightFear InducementFire ResistanceFlightForce FieldsHeat ResistanceInsanityInterstellar TravelInvulnerabilityJumpLongevityOmnilingualismRadiation ImmunityRegenerationSeismic PowerSelf-SustenanceShockwaves GenerationStealthSuper BreathToxin and Disease ResistanceVibration ManipulationVision - HeatVision - NightStatistics AmplificationTransformationUnderwater breathing', 24000);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Stefano', 'Valentini', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/valentini-3318351411036703347.jpg', 'AbsorptionAccelerated HealingAcrobaticsAgilityBanishBloodlustCold ResistanceCreationDark ArtsDurabilityEnduranceIntelligenceReflexesStaminaSuper SpeedTeleportationAdaptationBullet TimeEmotional Power UpEnergy AbsorptionFire ResistanceImmortalityInvisibilityMarksmanshipMind ControlMind Control ResistancePhasingRegeneration', 1000);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Lady Bullseye', 'Maki Matsumotu', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/maki-matsumotu-1157539782892406639.jpg', 'AgilityMarksmanshipMaster Martial ArtistPeak Human ConditionReflexesStaminaStealthWeapons MasterAcrobaticsDexterityEndurance', 58);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Mephisto (Lord Of Hatred)', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/mephisto-(lord-of-hatred)-8853637096770129445.jpg', 'CorruptionExtrasensory PerceptionImmortalityMadness ManipulationMagicNecromancyPossessionSoul ManipulationCryokinesisDimensional TravelElectrokinesisMagic ResistanceNon-Physical InteractionPortal CreationPower NullifierRegenerationStatistics ReductionSummoningToxin and Disease Control', 77000);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Iron Monger', 'Obadiah Stane', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/obadiah-stane-5733434994938301523.jpg', 'DurabilityEnergy BeamsIntelligenceMaster TacticianPower SuitRobotic EngineeringStaminaSuper SpeedSuper StrengthAgilityCold ResistanceEnergy AbsorptionEnergy BlastsExplosion ManipulationFire ResistanceFlightForce FieldsInvulnerabilityLevitationReflexesVision - NightVision - X-RayWeapon-based Powers', 520);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Dally (possesd by rubilax)', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/dally-(possesd-by-rubilax)-7612941956275718673.jpg', 'AgilityBerserk ModeDurabilityEnduranceJumpStaminaSuper StrengthBloodlustDemon PhysiologyGrappling/ClimbingHoly ResistanceInsanityJaw StrengthMaster Martial ArtistMultiple PersonalitiesNatural ArmorNatural WeaponsPain SuppressionRage PowerReflexesSupernatural ConditionSwordsmanshipUnholy ManipulationWeapon-based PowersApathyDark ArtsLarge Size', 271);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Indalecio', 'Dr. Lantis', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/dr.-lantis--5945987226963129460.jpg', 'AuraCold ResistanceCyborgizationEnergy BeamsEnergy ManipulationExplosion ManipulationFire ControlMagicPetrificationRadiation ImmunityToxin and Disease ResistanceWater ControlElectricity ResistanceEnhanced SensesFire ResistanceGravity ControlHeat ResistanceLevitationMagic ResistancePower AugmentationPower NullifierRobotic EngineeringStatistics AmplificationTeleportationTerrakinesisVitakinesisMind Transfer', 28000);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Hyena', 'Summer Day', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/summer-day--6106836038422475759.jpg', 'AgilityAnimal AttributesAnimal ControlAnimal Oriented PowersEnhanced SensesEnhanced SightEnhanced SmellSuper StrengthAccelerated Healing', 25);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Prince Of Power (Power Stone)', 'Otherone', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/otherone-5304043726822064531.jpg', 'DurabilityPeak Human ConditionStaminaSuper StrengthPower AugmentationPower Mimicry', 24000);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'The Infinite Man', 'Jaxon Rugarth', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/jaxon-rugarth--8114110369295742664.jpg', 'AbsorptionAccelerated HealingAcid ResistantsAgilityBanishClairvoyance ResistanceCold ResistanceCurse ResistanceDeath ManipulationDeath TouchDensity ControlDexterityElectricity ResistanceElement ControlEnduranceEnergy AbsorptionEnergy BeamsEnergy BlastsEnergy ManipulationEnergy ResistanceEnhanced HearingEnhanced MemoryEnhanced SensesEnhanced SightEnhanced SmellEnhanced TouchFire ControlFire ResistanceFlightForce FieldsGravity ControlHeat GenerationHeat ResistanceHigher Dimensional ManipulationIllusion ResistanceImmortalityInformation AnalysisIntelligenceInvulnerabilityLarge SizeLevitationLife ManipulationMaster TacticianMatter ManipulationMind Control ResistanceMolecular CombustionMolecular DissipationMolecular ImmobilizationMolecular ManipulationMolecular OscillationNigh-OmnipresencePhysics ManipulationPower AbsorptionPreparationRadiation AbsorptionRadiation ControlRadiation ImmunityReality WarpingReflexesRegenerationSize ChangingSoul ResistanceSpaceflightSpatial ManipulationStaminaTelekinesisTelepathy ResistanceTime ManipulationTime Manipulation ResistanceTime TravelTimeframe ControlToxin and Disease ResistanceVibration ManipulationVoid ManipulationWater ControlWeather ControlWind ControlAir ControlAntimatter ManipulationAstral ProjectionAstral TrapAstral TravelCausality ResistanceCorruption ResistanceCosmic AwarenessCreationDark Matter ManipulationDimensional AwarenessElectricity AbsorptionElectro-Magnetism ManipulationElectrokinesisEnergy ConstructsExistence Erasure ResistanceFear ManipulationHellfire ResistanceHoly ResistanceHyperkinesisIllusionsIndomitable WillIntangibilityInvisibilityLight ControlMagic ResistanceMaster Martial ArtistMatter AbsorptionMemory ManipulationMind ControlPower Absorption ImmunityQuantum ManipulationReality Warping ResistanceResurrectionSleep ManipulationSmoke ManipulationSoul ManipulationSound ManipulationSpatial AwarenessSubjective RealityTelepathyToxin and Disease ControlWeapons Master', 259000000);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Poison', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/poison-8916102462449536293.jpg', 'Hive-MindMind ControlPossessionDimensional TravelSymbiote Costume', 9);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Talia Al Ghul', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/talia-al-ghul-3485285246035315280.jpg', 'IntelligenceMaster Martial ArtistMaster TacticianSwordsmanshipStealthWeapon-based PowersWeapons MasterLongevityResurrection', 47);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Death', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/death--2731495292106554364.jpg', 'AbsorptionAdaptationAge ManipulationBanishClairvoyanceConceptual ManipulationCurse ResistanceDeath ManipulationDeath TouchDecay EmbodimentDimensional AwarenessDimensional TravelDivine PowersDurabilityEnhanced SensesExistence Erasure ResistanceGodly PhysiologyGrim ReapingIllusion ResistanceImmortalityLaw ManipulationMagic ResistanceMind Control ResistanceNigh-OmniscienceNothingness Aspect ManifestationOmnipresencePower NullifierSoul ManipulationSoul ResistanceStealthTeleportationAccelerated DevelopmentAgilityAvatar CreationBody PuppetryCorruptionCosmic AwarenessDanger SenseDensity ControlExistence ErasureFate ResistanceFear InducementIndomitable WillInvulnerabilityMind ControlReality Warping ResistanceSummoningTime Manipulation', 74000000);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Superboy-Prime', 'Kal-El', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/kal-el--5171244386238247035.jpg', 'Accelerated HealingAdaptationAgilityAttack NegationAuraAwakened PowerBerserk ModeBloodlustBullet TimeCold ResistanceDexterityDimensional TravelDurabilityDurability NegationEnergy AbsorptionEnergy ArmorEnergy BeamsEnergy EmbodimentEnergy ManipulationEnergy ResistanceEnhanced SensesEnhanced SightExistence Erasure ResistanceFire ResistanceFlightForce FieldsHeat ResistanceImmortalityIntelligenceInterstellar TravelInvulnerabilityJumpLevitationLongevityMind Control ResistanceMolecular OscillationPeak Human ConditionPortal CreationPower SuitQuantum ManipulationRadiation ImmunityReality WarpingReality Warping ResistanceReflexesRegenerationSelf-SustenanceStaminaSuper BreathSuper SpeedSuper StrengthTeleportationTime ManipulationTime Manipulation ResistanceTime TravelToxin and Disease ResistanceVaporising BeamsVibration ManipulationVision - HeatVision - X-RayAbsorptionAcausalityAccelerated DevelopmentAge ManipulationAnti-GravityAstral ProjectionChaos ManipulationClairvoyanceCloakingCorruption ResistanceCosmic AwarenessDamage BoostDamage ReductionDanger SenseDeath ManipulationDeconstructionDensity ControlDimensional AwarenessElectricity ResistanceElectrokinesisElement ControlEmotional Power UpEnduranceEnergy BlastsEnhanced HearingEnhanced TouchEntropy ProjectionExistence ErasureExplosion ManipulationExtrasensory PerceptionFate ResistanceGodly PhysiologyHeat GenerationHellfire ResistanceIndomitable WillInsanityIntangibilityInvisibilityMagic ResistanceMarksmanshipMaster Martial ArtistMaster TacticianMatter AbsorptionMatter ManipulationMolecular ManipulationMorality ManipulationPhotographic ReflexesPlot Manipulation ResistancePower AbsorptionPower ModificationPower SensePressure PointsPsionic PowersQwardian Power RingRage PowerSoul ResistanceSpaceflightTelekinesisTelepathyTerrakinesisVision - InfraredVision - MicroscopicVision - TelescopicVitakinesisVortex CreationWeapon-based PowersWeather ControlWind ControlMagic', 61000000);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Metal Elementor', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/metal-elementor-7765335015925367498.jpg', 'Metal ManipulationShapeshifting', 161);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Darth Malgus', 'Veradun', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/veradun--3385180529439784329.jpg', 'AcrobaticsAgilityAuraBloodlustBullet TimeClairvoyanceCold ResistanceDexterityDurabilityElectrical TransportElectro-Magnetism ManipulationElectrokinesisEnduranceEnhanced HearingEnhanced MemoryEnhanced SensesForce FieldsHeat ResistanceIntelligenceLongevityMaster Martial ArtistMaster TacticianMemory ManipulationPrecognitionPsychometryReflexesStaminaSuper SpeedSuper StrengthSwordsmanshipTechnopath/CyberpathTelekinesisTelepathyThe ForceToxin and Disease ResistanceWeapons MasterClairvoyance ResistanceDarkforce ManipulationElectricity AbsorptionElectricity ResistanceHeat GenerationJumpMind BlastMind ControlMind Control ResistancePower SenseRage PowerStealthTelepathy ResistanceVehicular Mastery', 36000);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Slipknot', 'Christopher Weiss', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/christopher-weiss-3464830431625756825.jpg', 'Weapons Master', 9);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Nicol Bolas (Pre-Mending)', 'Nicol', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/nicol--2075340867912842460.jpg', 'Accelerated HealingAnimal AttributesArcane MagicAttack NegationCold ResistanceCorruption ResistanceDark MagicDimensional TravelDurability NegationEnduranceEnergy ManipulationEnhanced MemoryEnhanced SensesEnhanced SightExtrasensory PerceptionFire ControlFire ResistanceFlightHeat ResistanceImmortalityInformation AnalysisLongevityMagicMagic AbsorptionMagic ResistanceMaster TacticianMind ControlMind Control ResistanceNatural ArmorNatural WeaponsPerfect RecollectionPower NullifierPreparationRegenerationRegeneration NegationSelf-SustenanceShapeshiftingSoul ResistanceTelepathyTelepathy ResistanceToxin and Disease ResistanceUnholy ManipulationUnholy ResistanceAir ControlAstral ProjectionAstral TravelAttack ReflectionAvatar CreationBody PuppetryClairvoyanceCorruptionCosmic AwarenessCreationCryokinesisCurse ManipulationCurse ResistanceDamage BoostDamage ReductionDeath TouchElectricity ResistanceElectrokinesisElement ControlEnergy ResistanceHeat GenerationHellfire ResistanceIllusion ResistanceIllusionsImmortality NegationIndomitable WillInformation ManipulationIntuitive aptitudeInvulnerabilityJaw StrengthLarge SizeMechanical AptitudeMemory ManipulationMind BlastNecromancyNon-Physical InteractionOmnilingualismPain ManipulationPerception ManipulationPortal CreationPower AbsorptionPower BestowalPower MimicryPower SenseSealingSense ManipulationSize ChangingSoul ManipulationStatistics AmplificationStatistics ReductionStatus Effect InducementSummoningTelekinesisTerrakinesisTime Manipulation ResistanceWater ControlWeather ControlWind ControlBanishDeath ManipulationDream ManipulationExistence ErasureExistence Erasure ResistanceGodly PhysiologyHellfire ManipulationHoly ManipulationHoly ResistanceInsanityLava ManipulationMultiple LimbsNon-CorporealPocket DimensionsReality Warping ResistanceTeleportationTime ManipulationToxin and Disease ControlTransmutation', 3000000);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Sun-Eater', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/sun-eater--2610429938379111831.jpg', 'Cold ResistanceElectricity ResistanceEnergy AbsorptionEnergy ResistanceFire ResistanceFlightInvulnerabilityLevitationPower AbsorptionVision - Heat', 13000);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Phantom Dharak', 'Dharak', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/dharak-4735040098648148723.jpg', 'AbsorptionAccelerated HealingAdaptationAgilityBerserk ModeBloodlustCold ResistanceDark ArtsDarkforce ManipulationDurabilityElasticityElectricity AbsorptionElectricity ResistanceEnduranceEnergy AbsorptionEnergy ArmorEnergy BeamsEnergy BlastsEnergy ConstructsEnergy EmbodimentEnergy ManipulationEnergy ResistanceEnhanced HearingEnhanced MemoryEnhanced SensesEnhanced SightEnhanced SmellEnhanced ThieveryEnhanced TouchFlightForce FieldsGrim ReapingHealHeat ResistanceHellfire ResistanceImmortalityIntelligenceInvulnerabilityNatural WeaponsPower SenseProjectionRadiation ImmunityRage PowerRegenerationSpaceflightStaminaSuper SpeedSuper StrengthToxin and Disease ResistanceVision - MicroscopicVision - NightVision - TelescopicAwakened PowerBullet TimeChanging ArmorDanger SenseDexterityDimensional TravelElement ControlEmotional Power UpFire ControlFire ResistanceInvisibilityJumpMaster TacticianNatural ArmorPortal CreationPreparationReality WarpingReflexesSize ChangingStealthSuper BreathTime Manipulation ResistanceWeather ControlIndomitable WillIntangibilityLongevityMind Control Resistance', 1000000);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Flux', 'Benjamin Tibbets', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/benjamin-tibbets-2154434263318020842.jpg', 'Absolute ConditionAccelerated HealingAgilityAwakened PowerBerserk ModeDamage BoostDexterityDurabilityEmotional Power UpEnduranceEnhanced ConditionGamma Mutant PhysiologyJumpMultiple PersonalitiesRage PowerStaminaAccelerated DevelopmentAdaptationBloodlustBullet TimeClairvoyance ResistanceCold ResistanceDamage TransferalEnhanced SensesFire ResistanceGrappling/ClimbingHeat ResistanceInvulnerabilityMarksmanshipMind Control ResistancePower AugmentationRadiation AbsorptionReflexesRegenerationWeapons MasterCorruption ResistanceElectricity AbsorptionElectricity ResistanceEnergy ResistanceIllusion ResistancePain SuppressionPower ModificationShockwaves GenerationStealthTelepathy Resistance', 29000);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Dex-Starr', 'Dexter', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/dexter-5553003460675847324.jpg', 'DurabilityEnergy BeamsEnergy BlastsEnergy ConstructsEnhanced SensesEnhanced SightEnhanced SmellFire ControlFire ResistanceFlightInterstellar TravelLantern Power RingRage InducementRage PowerEnduranceHeat GenerationHeat ResistancePlasma ManipulationReflexesSpaceflight', 1000);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Joker', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/joker-7896491608448058770.jpg', 'InsanityIntelligenceMadness ManipulationMarksmanshipStealthWeapon-based PowersWeapons MasterAcid ManipulationDeath ManipulationElectrokinesisElement ControlExplosion ManipulationMaster Martial ArtistPreparationToxin and Disease ControlToxin and Disease ResistanceVision - X-RayIllusionsMind ControlPossessionTransformation', 288);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Red Lantern', 'Guy Gardner', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/guy-gardner-3030440465464053595.jpg', 'Acid ResistantsAcidic SpitAfterimage CreationAgilityAnimationAttack ReflectionBerserk ModeBlood ManipulationBloodlustCold ResistanceCreationCryokinesisDexterityEmotional Power UpEnduranceEnergy AbsorptionEnergy ArmorEnergy BeamsEnergy BlastsEnergy ConstructsEnergy ManipulationEnergy ResistanceEnhanced HearingEnhanced MemoryEnhanced SensesEnhanced SightEnhanced TouchFire ControlFire ResistanceFlightHeat GenerationHeat ResistanceLantern Power RingPortal CreationRadiation ImmunityRage PowerReflexesShockwaves GenerationSpaceflightStatistics AmplificationTeleportationToxin and Disease ResistanceVision - MicroscopicVision - NightVision - TelescopicWeapon CreationWeapon SummoningWeapon-based PowersWeapons MasterAccelerated HealingAdaptationAir ControlCausality ResistanceClairvoyance ResistanceCorruption ResistanceCosmic AwarenessCurse ResistanceDimensional AwarenessElectricity ResistanceExplosion ManipulationIlluminationIllusion ResistanceInformation AnalysisIntangibilityInvisibilityInvulnerabilityJumpLight ControlMagic ResistanceMarksmanshipMaster Martial ArtistMaster TacticianMind Control ResistancePossession ResistancePower SuitPrecognitionRegenerationSpatial AwarenessTelepathy ResistanceTime TravelVision - X-RayExistence Erasure Resistance', 312000);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Wonder Woman', 'Diana Of Themyscira', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/diana-of-themyscira--269537995494897529.jpg', 'Accelerated DevelopmentAcrobaticsAgilityCold ResistanceDexterityDurabilityEnduranceEnhanced SensesFire ResistanceFlightGodly PhysiologyHeat ResistanceIndomitable WillIntelligenceJumpLongevityMarksmanshipMaster Martial ArtistReflexesStaminaSuper SpeedSuper StrengthWeapon-based PowersWeapons MasterEnhanced HearingEnhanced SightEnhanced SmellInstinctive ReactionInvulnerabilityMaster TacticianMind Control ResistanceSelf-SustenanceStealthTelepathy Resistance', 24000);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Death Kraken', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/death-kraken-9120222459798700526.jpg', 'Dimensional TravelEnhanced SmellLarge SizeSize ChangingStaminaSuper BreathSuper SpeedSuper StrengthTeleportationToxin and Disease ControlTransformationUnderwater breathingWater ControlDimensional AwarenessEnhanced SensesEnhanced SightInvulnerabilityMultiple LimbsSummoningSupernatural ConditionToxin and Disease Resistance', 75000);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Master Man', 'Max Lohmer', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/max-lohmer--7249890208250510634.jpg', 'DurabilityEnhanced HearingEnhanced MemoryEnhanced SensesEnhanced SightEnhanced SmellEnhanced TouchMarksmanshipMaster Martial ArtistStaminaSuper SpeedSuper StrengthWeapon-based PowersWeapons MasterAcrobaticsAgilityDexterityReflexesAccelerated HealingCold ResistanceEnergy ResistanceFire ResistanceHeat ResistanceJumpLongevityRadiation ImmunityRegenerationSelf-SustenanceToxin and Disease Resistance', 136);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Cupid', 'Carrie Cutter', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/carrie-cutter--3711121234519636848.jpg', 'StaminaAcrobaticsMarksmanshipStealthWeapons MasterAgilityReflexes', 24);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Choronzon', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/choronzon-2819559316618364279.jpg', 'Dark ArtsDark MagicIntelligenceShapeshiftingIllusions', 1000);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Scorpion', 'Carmilla Black', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/carmilla-black-5934323623967411989.jpg', 'AcrobaticsAgilityDexterityDisguise MasteryMarksmanshipMaster Martial ArtistMaster TacticianPeak Human ConditionReflexesStaminaToxin and Disease ControlToxin and Disease ResistanceWeapons MasterBloodlustCold ResistanceEnduranceEnhanced HearingEnhanced MemoryEnhanced SensesHeat ResistanceJumpPower Nullifier', 105);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Calamity Ganon', 'Ganondorf Dragmire', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/ganondorf-dragmire--8090126044161883942.jpg', 'Accelerated DevelopmentAccelerated HealingAnimal AttributesAnimal ControlAnimal Oriented PowersAvatar CreationBone ManipulationCorruptionCorruption ResistanceCurse ManipulationDark MagicDeath ManipulationDemon PhysiologyDurabilityElectrical TransportElectricity AbsorptionElectricity ResistanceElectro-Magnetism ManipulationElectrokinesisElement ControlEnergy BlastsEnergy ManipulationEnergy ResistanceEnhanced ConditionEnhanced HearingEnhanced MemoryEnhanced SensesEnhanced SightEnhanced SmellEnhanced ThieveryEnhanced TouchExplosion ManipulationFire ControlFire ResistanceHeat GenerationHeat ResistanceHellfire ManipulationHellfire ResistanceIllusionsImmortalityInvulnerabilityMadness ManipulationMagicMind ControlMind TransferSuper SpeedSuper StrengthSupernatural ConditionSwordsmanshipWater ControlWeapon CreationWeapon SummoningWeapon-based PowersWeapons MasterWeather ControlCreation', 110000);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Scorpion', 'MacDonald Gargan', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/macdonald-gargan--6099102988813253513.jpg', 'StaminaAccelerated DevelopmentAgilityCyborgizationJumpPower SuitReflexesStealthWallcrawling', 75);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'The Collector (What If...?)', 'Taneleer Tivan', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/taneleer-tivan-5889364416824494822.jpg', 'IntelligenceWeapons MasterAgilityBerserk ModeImmortalityLongevityTechnological PossessionWeapon CreationWeapon SummoningWeapon-based PowersJumpLarge Size', 93);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Black Mass', 'Geoffrey Thibodeux', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/geoffrey-thibodeux--8469018918540917820.jpg', 'DurabilityGravity ControlSize ChangingSuper StrengthTeleportation', 7);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Hela', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/hela-1892057575114490231.jpg', 'Accelerated HealingAdaptationAgilityAstral ProjectionBerserk ModeCold ResistanceCosmic AwarenessDanger SenseDarkforce ManipulationDeath ManipulationDeath TouchDexterityDimensional AwarenessDimensional TravelDurabilityEmpathyEnduranceEnergy ConstructsEnergy ManipulationEnergy ResistanceEnhanced HearingEnhanced MemoryEnhanced SensesEnhanced SightEnhanced SmellFire ControlFire ResistanceFlightForce FieldsGodly PhysiologyHair ManipulationHeat GenerationHeat ResistanceHellfire ManipulationIllusionsImmortalityIndomitable WillIntelligenceInterstellar TravelInvulnerabilityJumpLevitationNecromancyPhasingPortal CreationPower CosmicPsionic PowersReflexesSelf-SustenanceShapeshiftingStaminaSuper SpeedSuper StrengthTelekinesisTelepathyTeleportationToxin and Disease ResistanceVision - TelescopicWeapon-based PowersWeapons MasterAge ManipulationAnimal ControlAnimationEnergy AbsorptionEnergy BlastsExtrasensory PerceptionHypnokinesisLife ManipulationMagicMagic ResistanceMatter ManipulationMind ControlOmnilingualismPower BestowalPrecognitionRegenerationSoul ManipulationTransmutation', 825000);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Number 2', 'Unknown', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/unknown--6925405014817291415.jpg', 'MarksmanshipMaster Martial ArtistMaster TacticianWeapons MasterVision - X-Ray', 27);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Wendigo', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/wendigo-5452924040831258064.jpg', 'Accelerated HealingAdaptationAgilityBerserk ModeCold ResistanceDurabilityEnduranceEnhanced SensesEnhanced SmellHealIntelligenceAnimal AttributesBloodlustEnhanced HearingEnhanced MemoryEnhanced SightHeat ResistanceIllusion ResistanceJaw StrengthJumpLongevityMind Control ResistanceTelepathy ResistanceToxin and Disease ResistanceAnimal Oriented PowersCamouflageDigDimensional TravelElectricity ResistanceEmpathyFire ResistanceGodly PhysiologyGrappling/ClimbingHellfire ResistanceImmortalityInvulnerabilityLarge SizeLatent AbilitiesMagicMagic Resistance', 1000);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Look-See', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/look-see--8225219983408542665.jpg', 'AgilityApathyDurabilityEnduranceEnhanced SensesFear InducementImmortalityIndomitable WillIntelligenceReflexesStaminaStealthTelekinesisTeleportationAccelerated HealingBloodlustDexterityEnhanced HearingFear ManipulationInsanityIntuitive aptitudeShapeshiftingTelepathyInvulnerabilityMaster TacticianPrecognition', 267);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Lex Luthor', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/lex-luthor-2676857305898568600.jpg', 'HackingIntelligenceMaster TacticianPreparationPower SuitPrecognition', 15);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Shredder', 'Oroku Saki', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/oroku-saki--6028188006078067493.jpg', 'AgilityDexterityDurabilityEnduranceIntelligenceMarksmanshipMaster Martial ArtistMaster TacticianPeak Human ConditionReflexesStaminaStealthSuper StrengthWeapon-based PowersWeapons MasterAdaptationChi ManipulationJumpNinjutsu', 89);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'SCP-3166', 'Gorefield', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/gorefield-1268575876359671498.jpg', 'Accelerated HealingDurabilityFlightStaminaSuper SpeedSuper StrengthAnimal AttributesEnhanced HearingEnhanced MemoryEnhanced SensesEnhanced SightEnhanced SmellImmortalityJumpPhasingRegenerationShapeshiftingSuper BreathToxin and Disease Resistance', 543);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Clone Zero', 'Ling Zero', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/ling-zero-2854256337656039364.jpg', 'Accelerated HealingAdaptationAgilityAuraChi ManipulationCloth ManipulationDanger SenseDark ArtsDexterityDisguise MasteryDurabilityEnergy ArmorEnergy ManipulationEnhanced MemoryEnhanced SensesForce FieldsIntelligenceJumpMaster Martial ArtistMaster TacticianNatural ArmorPeak Human ConditionPower MimicryPower SuitReflexesShapeshiftingShockwaves GenerationStaminaSuper StrengthWeapon-based PowersAbsolute ConditionBlack Hole ManipulationDarkforce ManipulationDuplicationElectrokinesisEmpathyEnduranceEnergy BlastsEnergy ConstructsEnhanced ConditionEnhanced HearingEnhanced SightForce SpeedGlidingLatent AbilitiesLevitationLongevityMarksmanshipNatural WeaponsPower SensePreparationRadiation ImmunityRegenerationSelf-DestructionSelf-SustenanceShadow ManipulationSpatial AwarenessStealthToxin and Disease ResistanceWeapons MasterAcrobaticsIntuitive aptitudeNon-Physical InteractionSwordsmanship', 7000);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Morgan Le Fay', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/morgan-le-fay--6709585629769086589.jpg', 'AbsorptionAccelerated HealingAfterimage CreationAge ManipulationAnimal Oriented PowersArcane MagicAstral ProjectionAstral TrapAstral TravelBanishBlood ManipulationChi ManipulationCold ResistanceCreationCurse ManipulationDark MagicEnergy AbsorptionEnergy BlastsEnergy ManipulationEnergy ResistanceEnhanced HearingEnhanced MemoryEnhanced SensesEnhanced SightFire ResistanceFlightForce FieldsHeat GenerationHeat ResistanceIllusion ResistanceIllusionsImmortalityIndomitable WillIntelligenceInvulnerabilityMagicMagic AbsorptionMagic ResistanceNecromancyPower AbsorptionPower Absorption ImmunityPower BestowalPower MimicryPower ModificationPower NullifierRadiation ImmunityReality WarpingReality Warping ResistanceRegenerationResurrectionSealingShapeshiftingSpaceflightSpatial ManipulationStaminaStatistics AmplificationSuper SpeedSuper StrengthTeleportationTerrakinesisTime ManipulationTime TravelToxin and Disease ControlToxin and Disease ResistanceTransmutationAgilityAnimal ControlAntimatter ManipulationAttack NegationAttack ReflectionAuraBlack Hole ManipulationClairvoyanceClairvoyance ResistanceCorruption ResistanceCurse ResistanceDamage BoostDamage ReductionDamage TransferalDarkforce ManipulationDexterityDimensional AwarenessDimensional TravelElectricity ResistanceEnduranceEnergy ConstructsExistence ErasureExistence Erasure ResistanceExplosion ManipulationFood ManipulationHellfire ResistanceHigher Dimensional ManipulationHoming AttackIntangibilityInterstellar TravelInvisibilityLevitationMatter AbsorptionMatter ManipulationMemory ManipulationMind BlastMind ControlMind Control ResistanceMind TransferMolecular ManipulationOrganic ManipulationPhasingPlot Manipulation ResistancePossession ResistancePower AugmentationPower SensePrecognitionPreparationProjectionReflexesShadow ManipulationShockwaves GenerationSleep ManipulationSmoke ManipulationSoul ManipulationSoul ResistanceSpatial AwarenessSpatial CommunicationSubjective RealityTelepathyTelepathy ResistanceTime Manipulation ResistanceTimeframe ControlDeath ManipulationDream ManipulationLife Manipulation', 7000000);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Trespasser', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/trespasser--7169046181469663594.jpg', 'Amphibious RespirationAnimal AttributesEnduranceLarge SizeNatural WeaponsCold ResistanceElectricity ResistanceEnhanced SensesFire ResistanceHeat ResistanceJaw StrengthMultiple LimbsNatural ArmorToxin and Disease ResistanceCorruptionIllumination', 209);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Frost', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/frost--5860768457199039580.jpg', 'Accelerated DevelopmentAccelerated HealingAcrobaticsAgilityChi ManipulationCold ResistanceDanmakuDexterityDurabilityElectricity ResistanceEnduranceEnergy BeamsEnergy BlastsEnhanced ConditionEnhanced SensesFire ResistanceFlightHealHeat ResistanceHoming AttackIntelligenceInvulnerabilityJumpLatent AbilitiesLongevityMarksmanshipMaster Martial ArtistMaster TacticianPeak Human ConditionRadiation ImmunityReflexesSeismic PowerStaminaStealthSuper SpeedSuper StrengthToxin and Disease ResistanceAbility ShiftAbsorptionAfterimage CreationAuraClairvoyanceEnergy AbsorptionEnergy ManipulationEnergy ResistanceEnhanced HearingEnhanced SightHeat GenerationInterstellar TravelLevitationLight ControlNatural ArmorPower SenseRadar SenseRobotic EngineeringShockwaves GenerationTransformationWeapon CreationWind ControlRegenerationSelf-Sustenance', 29000);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Murisam', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/murisam--3026734290179241147.jpg', 'DurabilityHealPeak Human ConditionStaminaSuper SpeedSuper StrengthAcrobaticsAgilityDexterityEnduranceEnhanced ConditionJumpMaster Martial ArtistReflexes', 66);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Sailor Galaxia', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/sailor-galaxia-3910152960580797459.jpg', 'Energy BlastsEnergy ManipulationForce FieldsHoly ManipulationMagicMatter ManipulationMind ControlReality WarpingSoul ManipulationClairvoyanceConceptual ManipulationCosmic AwarenessCreationDeath ManipulationDeconstructionDimensional TravelDurability NegationElectrokinesisEnergy AbsorptionEnhanced SensesExistence Erasure ResistanceExtrasensory PerceptionFlightImmortalityLife ManipulationMaster TacticianMind Control ResistanceNon-Physical InteractionPower BestowalPower NullifierPrecognitionRadiation ImmunityRegenerationSoul ResistanceSpatial ManipulationTelepathyTeleportationToxin and Disease Resistance', 578000);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Twice', 'Jin Bubaigawara', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/jin-bubaigawara-5270500299847715398.jpg', 'DuplicationInsanityMultiple Personalities', 125);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Chara', 'Chara Dreemurr', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/chara-dreemurr--1053789673845928366.jpg', 'ResurrectionStaminaSuper SpeedSuper StrengthAgilityReflexesSoul ManipulationTime ManipulationTime TravelDamage BoostDurability NegationIndomitable WillJumpPossession', 242000);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Samaritan', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/samaritan-5587885667787689024.jpg', 'Enhanced MemoryIntelligenceMaster TacticianStealthTechnological PossessionPrecognition', 468);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Mom', 'Mommy Mearest', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/mommy-mearest-209144986348504867.jpg', 'Accelerated DevelopmentAccelerated HealingBroadway ForceDurabilityEnhanced ConditionEnhanced HearingEnhanced SensesEnhanced SmellIntelligencePeak Human ConditionPressure PointsReflexesSpatial AwarenessStaminaSuper SpeedSuper StrengthTelekinesisTelepathyBerserk ModeChi ManipulationEnduranceEnhanced MemoryEnhanced SightFire ResistanceGlidingIllusionsMagicMaster TacticianMind ControlRage PowerRegenerationSealingSoul ManipulationSoul ResistanceTeleportationToon ForceToxin and Disease ResistanceVision - InfraredWeapon CreationDemon Physiology', 2000);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Sofia Stepanova', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/sofia-stepanova-85942052255714982.jpg', 'IntelligencePeak Human ConditionStaminaMarksmanshipMaster Martial ArtistMaster TacticianWeapons MasterEndurance', 40);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Raditz', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/raditz-1186447823287045133.jpg', 'AgilityChi ManipulationDurabilityEnergy BeamsEnergy BlastsFlightHealIntelligenceJumpPeak Human ConditionStaminaSuper SpeedSuper StrengthAccelerated DevelopmentAccelerated HealingAcrobaticsAfterimage CreationBullet TimeCold ResistanceDanmakuDexterityElectricity ResistanceEnduranceEnergy ManipulationEnhanced HearingEnhanced MemoryEnhanced SensesEnhanced SightEnhanced SmellFire ResistanceHeat GenerationHeat ResistanceIndomitable WillInvulnerabilityLongevityMarksmanshipMaster Martial ArtistReflexesVaporising BeamsAnimal AttributesBloodlustClairvoyanceElectrokinesisExplosion ManipulationGadget UsageLatent AbilitiesPower SensePower SuitReactive EvolutionRobotic EngineeringTransformation', 803);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Lord T', 'Tantalus', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/tantalus-8911890221157075912.jpg', 'Death TouchDurabilityEnhanced SensesIntelligenceReflexesStaminaSuper SpeedSuper StrengthAccelerated HealingAgilityCold ResistanceDexterityEnduranceImmortalityInvulnerabilityJumpMaster TacticianRegenerationStealthToxin and Disease ResistanceWeapons Master', 907);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Jinx', 'Powder', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/powder-4738696443109066819.jpg', 'DexterityEnduranceExplosion ManipulationInsanityMarksmanshipMaster Martial ArtistReflexesStaminaStatistics ReductionStealthVehicular MasteryAcrobaticsCold ResistanceElectrokinesisEnhanced HearingEnhanced MemoryEnhanced SensesEnhanced SightEnhanced TouchExtrasensory PerceptionFlightHeat ResistanceIllusionsJumpMaster TacticianPreparationStatistics AmplificationToxin and Disease ResistanceWeapons Master', 172);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Ulik', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/ulik--1469129298542836075.jpg', 'Berserk ModeCold ResistanceDexterityEmotional Power UpEnduranceFate ResistanceFire ResistanceHeat ResistanceJumpMaster Martial ArtistMaster TacticianRadiation ImmunityRage PowerReflexesShockwaves GenerationStaminaToxin and Disease ResistanceWeapons MasterAccelerated HealingAcid ResistantsAcrobaticsAgilityDensity ControlElectricity ResistanceEnergy ResistanceEnhanced HearingEnhanced SensesEnhanced SightEnhanced SmellEnhanced TouchRegenerationSound ManipulationSwordsmanshipFlight', 24000);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Fembots', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/fembots-6870752461699762801.jpg', 'DurabilityStaminaEnduranceMarksmanshipMaster Martial ArtistMaster TacticianWeapon-based Powers', 38);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Deathstroke (Godkiller)', 'Slade Wilson', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/slade-wilson--2749452904345154979.jpg', 'Accelerated DevelopmentAccelerated HealingAcrobaticsAgilityAttack ReflectionBloodlustDanger SenseDexterityDurabilityEnduranceEnergy AbsorptionFire ResistanceHeat GenerationHeat ResistanceImmortalityImmortality NegationIntelligenceMagicMagic AbsorptionMagic ResistanceMarksmanshipMaster Martial ArtistMaster TacticianPower SuitReflexesRegenerationRegeneration NegationStaminaStealthSuper SpeedSuper StrengthSwordsmanshipToxin and Disease ResistanceVehicular MasteryWeapon SummoningWeapon-based PowersWeapons MasterAbility ShiftAbsorptionAcausalityAcid ResistantsAdaptationBerserk ModeBlessedCausality ResistanceClairvoyance ResistanceCorruption ResistanceCurse ResistanceDamage ReductionDamage TransferalDeath TouchDurability NegationElectricity AbsorptionElectricity ResistanceEnergy BeamsEnergy BlastsEnergy ResistanceEnhanced HearingEnhanced MemoryEnhanced SensesEnhanced SightEnhanced SmellEnhanced ThieveryExistence Erasure ResistanceFate ResistanceHackingIllusion ResistanceIndomitable WillInformation AnalysisLatent AbilitiesLongevityMechanical AptitudeMind Control ResistancePossession ResistancePower Absorption ImmunityPower Mimicry ImmunityPressure PointsRadiation ImmunityRage PowerReactive Power LevelReality Warping ResistanceRobotic EngineeringSelf-SustenanceShockwaves GenerationSoul ResistanceSpace SurvivabilityStandsSummoningTelepathy ResistanceTime Manipulation ResistanceTransformationUnholy ResistanceVision - CryoVision - HeatVision - InfraredVision - NightWill Of God', 226000);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Toichiro Suzuki', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/toichiro-suzuki--660166329840022628.jpg', 'AbsorptionAccelerated HealingAttack NegationAttack ReflectionAuraCloningCold ResistanceCryokinesisDamage BoostDamage ReductionDurabilityDurability NegationElectrokinesisElement ControlEnergy AbsorptionEnergy ArmorEnergy BeamsEnergy BlastsEnergy ConstructsEnergy ManipulationEnergy ResistanceExplosion ManipulationFire ControlFire ResistanceFlightForce FieldsGravity ControlHeat GenerationHeat ResistanceJumpLevitationMind Control ResistancePower AbsorptionPower BestowalShockwaves GenerationSocial InfluencingSuper SpeedSuper StrengthTelekinesisWind ControlAgilityReflexesRegeneration', 5000);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Dr. Jill Roberts', 'Jill Roberts', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/jill-roberts-3402944078638108106.jpg', 'IntelligencePeak Human ConditionStaminaHackingMarksmanshipMaster Martial ArtistMaster TacticianWeapons MasterEndurance', 38);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Ursula (Power of the Trident)', 'Ursula', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/ursula--5786547146957697590.jpg', 'Amphibious RespirationDurabilityFear InducementIndomitable WillLarge SizeTentaclesUnderwater breathingWater ControlWeather ControlAccelerated HealingAnimal AttributesAnimal Oriented PowersDark MagicEnduranceEnergy BeamsEnhanced SensesInsanityMagic ResistanceSize ChangingStatistics AmplificationDivine PowersLongevityMagicMaster TacticianReflexesVision - NightWishing', 1000);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Cheshire', 'Jade Nguyen', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/jade-nguyen--9143380112165550228.jpg', 'StaminaAcrobaticsAgilityMarksmanshipMaster Martial ArtistStealthToxin and Disease ControlToxin and Disease ResistanceWeapons Master', 62);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Arch Illager', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/arch-illager-5906045942500115502.jpg', 'Arcane MagicAuraEnergy ConstructsIllusionsMagicDark ArtsEnergy BlastsEnergy ManipulationForce FieldsHoming AttackLevitationPlasma ManipulationPower AugmentationProjectionRune MagicSoul ManipulationSpirit ControlAstral ProjectionBerserk ModeCreationFlightTelekinesis', 2000);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Ganimes (Showa)', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/ganimes-(showa)-4240287070962402541.jpg', 'Amphibious RespirationAnimal AttributesAnimal Oriented PowersLarge SizeNatural WeaponsSubstance SecretionCold ResistanceElectricity ResistanceFire ResistanceHeat ResistanceNatural ArmorRadiation ImmunityToxin and Disease Resistance', 123);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Dweller-in-Darkness', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/dweller-in-darkness-495547744389253589.jpg', 'Accelerated HealingAgilityAnimal AttributesAnimal Oriented PowersClairvoyanceCold ResistanceDurabilityEnduranceFire ResistanceIntelligenceLarge SizeRadiation ImmunityReflexesStaminaSuper SpeedSuper StrengthToxin and Disease ResistanceAbsorptionCorruption ResistanceDexterityElectricity ResistanceEnergy AbsorptionEnergy ResistanceFlightHeat ResistanceImmortalityInvulnerabilityNon-Physical InteractionPsionic PowersRegenerationSelf-SustenanceSoul ManipulationSoul ResistanceStealthTelepathyAnimal ControlIlluminationLatent AbilitiesLife ManipulationMaster Tactician', 3000);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Dark Meta Knight (Dark Meta Knight)', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/dark-meta-knight-(dark-meta-knight)--3413570599486796987.jpg', 'AcrobaticsAir ControlDurabilityElasticityEnduranceFlightImmortalityIntelligenceLongevityNon-Physical InteractionRegenerationSelf-SustenanceShapeshiftingSpaceflightStaminaStrength ForceSuper BreathSuper SpeedSuper StrengthToon ForceWeapons MasterAccelerated DevelopmentAccelerated HealingDuplicationEnergy AbsorptionEnergy ArmorEnergy BlastsEnergy ResistanceFire ControlFire ResistanceForce SpeedPower CosmicWind Control', 796000);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Cull Obsidian', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/cull-obsidian-1420978687119608255.jpg', 'Cold ResistanceDurabilityEnduranceEnergy ResistanceHeat ResistanceIntelligenceInvulnerabilityJumpRadiation ImmunityStaminaSuper SpeedSuper StrengthToxin and Disease ResistanceWeapons MasterAccelerated HealingAgilityDexterityEnhanced SensesFire ResistanceMarksmanshipReflexesRegenerationStealthWeapon-based PowersAcrobaticsAttack ReflectionMaster Martial Artist', 466);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Death Phantom', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/death-phantom-510113196747476472.jpg', 'CorruptionFlightIllusionsLevitationMind ControlAvatar CreationClairvoyanceDimensional TravelEnergy AbsorptionEnergy BlastsFusionGravity ControlNon-CorporealNon-Physical InteractionPower BestowalRadiation ImmunitySpatial ManipulationTime Manipulation', 20000);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Ben', 'X5-493', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/x5-493--1622513127813069898.jpg', 'DurabilityPeak Human ConditionStaminaSuper SpeedSuper StrengthEnduranceEnhanced HearingEnhanced MemoryEnhanced SensesEnhanced SightEnhanced SmellEnhanced TouchInsanityMarksmanshipMaster Martial ArtistMaster TacticianReflexesVehicular MasteryVision - NightVision - TelescopicWeapons MasterAcrobaticsAdaptationAgilityDexterityJumpRegenerationToxin and Disease Resistance', 96);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Dr Cortex', 'Doctor Neo Cortex', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/doctor-neo-cortex--6531360048236379593.jpg', 'Energy BlastsTransmutationCyborgizationForce FieldsHackingHoming AttackMind BlastPower AugmentationAnimal ControlElectrokinesisPower Bestowal', 324);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Sharra', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/sharra-8048590624465765380.jpg', 'Accelerated HealingBiokinesisClairvoyanceCold ResistanceCosmic AwarenessDexterityDurabilityElement ControlEnduranceEnergy ConstructsEnergy ManipulationEnhanced SensesFire ResistanceFlightHeat ResistanceIlluminationIntelligenceInterstellar TravelInvulnerabilityLife ManipulationMind Control ResistanceRadiation ImmunityReflexesStaminaSummoningSuper SpeedSuper StrengthTeleportationTerrakinesisToxin and Disease ResistanceWater ControlWeather ControlWind ControlAgilityAuraChi ManipulationCreationEnergy BeamsEnergy BlastsEnergy ResistanceImmortalityJumpLight ControlPower AugmentationPower BestowalReality WarpingRegenerationSelf-SustenanceStealthTelekinesisTelepathy ResistanceVitakinesisCurse ManipulationDimensional TravelOmnilingualismWishing', 414000);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Ames White', 'Ames Sandeman', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/ames-sandeman--2924900129660385880.jpg', 'DurabilityPain SuppressionPeak Human ConditionStaminaSuper SpeedSuper StrengthEnduranceMarksmanshipMaster Martial ArtistMaster TacticianWeapons MasterAcrobaticsAgilityDexterityEnhanced SightIndomitable WillJumpTelekinesisToxin and Disease Resistance', 66);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Jason Voorhees', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/jason-voorhees--5969316062532451345.jpg', 'Berserk ModeBloodlustCold ResistanceCurse ResistanceDurabilityEnhanced HearingEnhanced SensesFear ManipulationFire ResistanceHeat ResistanceImmortalityInsanityInvulnerabilityRadiation ImmunityReflexesRegenerationStaminaSuper SpeedSuper StrengthToxin and Disease ResistanceZombie PhysiologyAccelerated HealingAgilityDexterityElectricity ResistanceEnduranceFear InducementHypnokinesisInorganic PhysiologyInstinctive ReactionJumpPain SuppressionSelf-SustenanceUnderwater breathing', 249);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Gigan (Millennium)', 'Gigan', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/gigan-432303300524720778.jpg', 'Accelerated HealingBionicsCyborgizationDurabilityEnergy BeamsEnergy BlastsEnhanced SensesFlightHunters InstinctIntelligenceInterstellar TravelJaw StrengthLarge SizeRadiation ImmunityVaporising BeamsAgilityCold ResistanceEnergy ResistanceFire ResistanceInvulnerabilityJumpLevitationNatural WeaponsSpaceflightToxin and Disease Resistance', 900);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Wahoo', 'Speed Demon', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/speed-demon--3117891513972798793.jpg', 'Accelerated HealingCosmic AwarenessCreationDemon PhysiologyDimension StorageDimensional AwarenessDimensional TravelEnergy BlastsEnergy ManipulationEnhanced MemoryEnhanced SensesEnhanced SightExistence ErasureFlightGlidingInterstellar TravelInvulnerabilityNigh-OmnipresencePhasingPhotographic DeductionPhotographic ReflexesPlot Manipulation ResistancePocket DimensionsPossessionPossession ResistancePostcognitionPower AbsorptionPower Absorption ImmunityPower AugmentationPower BestowalPower MimicryPower NullifierPower SensePrecognitionProjectionReality WarpingReality Warping ResistanceSpace SurvivabilitySpaceflightSuper SpeedSuper StrengthSupreme PowerTime ManipulationTime Manipulation ResistanceTime TravelTimeframe ControlWeapon Creation', 63000000);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Thumbskull', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/thumbskull--6022033965134495387.jpg', 'DexterityPeak Human ConditionStaminaSuper SpeedSuper StrengthToxin and Disease ResistanceAgilityElectricity ResistanceEnduranceEnhanced HearingFire ResistanceHeat ResistanceJump', 43);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Toki', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/toki--7867371788469187681.jpg', 'Ability ShiftAcausalityAccelerated DevelopmentAccelerated HealingAcrobaticsAdaptationAgilityAmberAttack NegationAttack ReflectionAuraCausality ManipulationChi ManipulationClairvoyanceClairvoyance ResistanceCompassion InducementConceptual ManipulationDamage BoostDamage ReductionDamage TransferalDanmakuData ManipulationDeath ManipulationDeath TouchDurabilityEmotional Power UpEmpathyEnduranceEnhanced HearingEnhanced MemoryEnhanced SensesEnhanced SightEnhanced SmellEnhanced TouchFate ManipulationFate ResistanceGodly PhysiologyHealHope InducementInformation AnalysisInformation ManipulationInstinctive ReactionIntangibilityIntelligenceIntuitive aptitudeInvulnerabilityLife ManipulationLove InducementMaster Martial ArtistMemory ManipulationMind ControlMind Control ResistanceMorality ManipulationNinjutsuOcular TechniquesPain ManipulationPain SuppressionPeak Human ConditionPerception ManipulationPerfect RecollectionPlot Manipulation ResistancePower AugmentationPower MimicryPower NullifierPressure PointsProbability ManipulationProjectionPsionic PowersRage InducementRage PowerReactive EvolutionReactive Power LevelReflexesSense ManipulationSocial InfluencingSpatial AwarenessSpatial ManipulationSpinjitzuStaminaStatistics AmplificationStatistics ReductionStatus Effect InducementStealthSuper StrengthToxin and Disease ControlToxin and Disease ResistanceTruth ManipulationAbsolute ConditionAfterimage CreationAge ManipulationAnimal AttributesAnimal ControlAstral ProjectionAstro ForceAwakened PowerBerserk ModeBiokinesisBloodlustCold ResistanceCorruption ResistanceCryokinesisDanger SenseDexterityDream ManipulationDuplicationDurability NegationElectricity ResistanceElement ControlEnergy BlastsEnergy ConstructsEnergy EmbodimentEnergy ManipulationEnergy ResistanceEnhanced ConditionEntropy ProjectionFear InducementFear ManipulationFire ResistanceHeat ResistanceHoly ManipulationHoly ResistanceHypnokinesisIlluminationIllusionsJumpLight ControlMagic ResistanceMatter ManipulationMind BlastMind TransferMolecular DissipationMolecular ImmobilizationNon-Physical InteractionNothingness Aspect ManifestationOmnilingualismOrigin ManipulationPhotographic ReflexesPhysical AnomalyPhysics ManipulationPower BestowalPower ModificationPreparationReality Warping ResistanceSeparationSleep ManipulationSoul ManipulationSoul ResistanceSpatial CommunicationSubatomic ManipulationTelepathy ResistanceTerrakinesisVibration ManipulationVision - MicroscopicVision - NightVision - TelescopicVitakinesisWater ControlWeather ControlWillpower InducementWillpower ManipulationWind ControlMetal ManipulationReality WarpingRegenerationVision - CryoVoid Manipulation', 170000);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'The Drowned', 'Bryce Wayne', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/bryce-wayne-5574775539789022831.jpg', 'AcrobaticsAgilityAnimal ControlCold ResistanceDexterityEnduranceEnergy ResistanceEnhanced HearingEnhanced MemoryEnhanced SensesEnhanced SightIntelligenceMaster Martial ArtistMaster TacticianPower ModificationReflexesStaminaStatistics AmplificationSummoningSuper SpeedSuper StrengthSwordsmanshipUnderwater breathingVehicular MasteryWater ControlWeapons MasterAccelerated HealingBloodlustClairvoyance ResistanceEnergy BlastsEnergy ManipulationFire ResistanceHeat ResistanceOrganic ManipulationRadiation ImmunityRegenerationToxin and Disease Resistance', 626);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Atraxa, Praetors'' Voice', 'Atraxa', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/atraxa--2548839656340043085.jpg', 'Accelerated HealingAcid ResistantsAngel PhysiologyCold ResistanceCorruptionCorruption ResistanceCyborgizationDark MagicElectricity ResistanceEnduranceEnergy ResistanceEnhanced SensesExtrasensory PerceptionFire ResistanceFlightHeat ResistanceInorganic PhysiologyLongevityMagic ResistanceMultiple LimbsSelf-SustenanceStatus Effect InducementSubstance SecretionToxin and Disease ResistanceAccelerated DevelopmentAcid ManipulationAgilityAir ControlAnimal ControlAttack NegationAttack ReflectionCurse ResistanceDamage ReductionDurability NegationElectrokinesisElement ControlEnergy BlastsEnergy ManipulationFear InducementForce FieldsGadget UsageGlidingHellfire ResistanceHoly ManipulationHoly ResistanceHope InducementIlluminationIllusion ResistanceIndomitable WillIntuitive aptitudeInvulnerabilityLevitationLight ControlMagicMarksmanshipMechanical AptitudeMetal ManipulationMind Control ResistanceNatural ArmorNatural WeaponsNecromancyNon-Physical InteractionOrganic ManipulationPlant ControlPossession ResistancePower NullifierPsionic PowersReflexesRegeneration NegationResurrectionSoul ManipulationSoul ResistanceStatistics AmplificationStatistics ReductionTelepathy ResistanceToxin and Disease ControlUmbrakinesisUnholy ManipulationUnholy ResistanceVaporising BeamsWater ControlWeapon-based PowersWind ControlAuraBlood ManipulationCurse ManipulationDamage TransferalDeath ManipulationDeath TouchEnergy AbsorptionEnergy ConstructsIllusionsImmortalityInformation AnalysisLarge SizeLife ManipulationMagic AbsorptionMaster TacticianMeltingPower AugmentationPower BestowalPreparationPurificationTelepathyWeapons Master', 16000);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Sephiroth (Safer Sephiroth)', 'Sephiroth', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/sephiroth-6385759778777286586.jpg', 'BloodlustClairvoyanceCold ResistanceCryokinesisDeath ManipulationDurabilityDurability NegationElectrokinesisElement ControlElemental TransmogrificationEnergy BlastsEnhanced SensesExplosion ManipulationExtrasensory PerceptionFire ControlFire ResistanceFlightGodly PhysiologyGravity ControlHealHeat GenerationHeat ResistanceImmortalityIntelligenceLarge SizeLevitationLife ManipulationLongevityMagicMatter ManipulationMind Control ResistanceNatural WeaponsPeak Human ConditionPossessionPower NullifierRadiation ControlRadiation ImmunityRegenerationSense ManipulationSoul ManipulationSoul ResistanceSpaceflightStaminaStatistics AmplificationStatistics ReductionSuper SpeedSupernatural ConditionTelekinesisTerrakinesisTime ManipulationTime Manipulation ResistanceWeapons MasterAbsorptionAccelerated HealingAdaptationBiokinesisBullet TimeCorruption ResistanceDamage BoostDamage ReductionElectricity ResistanceEmpathyEnergy AbsorptionEnergy ManipulationExistence ErasureHoly ResistanceIllusionsIntangibilityMemory ManipulationMind ControlPain ManipulationParalysisPerception ManipulationPetrificationPower Absorption ImmunityProjectionRegeneration NegationShapeshiftingSleep ManipulationSummoningTelepathyToxin and Disease ControlToxin and Disease ResistanceTransmutationWeapon CreationAstral ProjectionDimensional TravelPocket Dimensions', 2000000);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Summa-verminoth', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/summa-verminoth--2456976168508897663.jpg', 'Animal AttributesCold ResistanceDurabilityEnhanced SensesFire ResistanceLongevityStaminaSuper SpeedSuper StrengthAccelerated HealingAgilityAnimal Oriented PowersAuraDexterityElectrical TransportElectricity AbsorptionElectricity ResistanceElectrokinesisEnduranceEnergy ResistanceFire ControlFlightHeat GenerationHeat ResistanceInterstellar TravelInvulnerabilityRadiation ImmunityReflexesRegenerationStealthToxin and Disease ResistanceVision - NightEnergy BlastsVision - TelescopicWeather Control', 6000);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Bane', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/bane--1233749596664541504.jpg', 'DurabilityIntelligencePeak Human ConditionStaminaEnduranceMaster Martial ArtistMaster TacticianWeapons MasterBerserk ModeMarksmanshipReflexes', 45);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Chakravartin (The Golden Spider)', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/chakravartin-(the-golden-spider)-2056916866282309831.jpg', 'Death ManipulationDurabilityEnduranceEnergy ManipulationFlightForce FieldsIllusionsImmortalityIntelligenceLarge SizeLife ManipulationPocket DimensionsPossessionReality WarpingRegenerationSelf-SustenanceShapeshiftingSize ChangingTelekinesisTelepathyTeleportationTime ManipulationTransformationWeapon CreationWeapons MasterAbsorptionAccelerated HealingCreationDivine PowersElasticityEnergy AbsorptionEnergy ArmorEnergy BeamsEnergy BlastsMaster Martial Artist', 850000);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Malekith', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/malekith-8808166580736314600.jpg', 'AbsorptionCreationDarkforce ManipulationElement ControlEnergy ManipulationLongevityMaster Martial ArtistMatter ManipulationPerception ManipulationRegenerationSize ChangingTelekinesisTransmutationWeapons MasterGravity Control', 294);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Faora', 'Faora-Ul', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/faora-ul--5489344427370132401.jpg', 'AgilityCold ResistanceDurabilityElectricity ResistanceEnduranceEnergy ResistanceEnhanced SensesFire ResistanceHeat ResistanceIntelligenceJumpReflexesStaminaStealthSuper SpeedSuper StrengthToxin and Disease ResistanceAccelerated HealingAcrobaticsDexterityEnergy BeamsEnergy BlastsEnhanced HearingEnhanced SightEnhanced SmellHeat GenerationInvulnerabilityMarksmanshipMaster Martial ArtistRadiation ImmunitySelf-SustenanceVision - NightVision - TelescopicVision - X-RayWeapons MasterMaster TacticianRegeneration', 7000);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Metallo', 'John Corben', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/john-corben--1602845514405098673.jpg', 'DurabilityStaminaSuper StrengthAgilityEnergy BlastsEnhanced SensesRadiation ControlSelf-SustenanceShapeshiftingTechnopath/Cyberpath', 257);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Nyx', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/nyx--2517594392559926444.jpg', 'AbsorptionAccelerated HealingAcid ResistantsAgilityAir ControlArcane MagicAttack ReflectionBlack Hole ManipulationClairvoyanceClairvoyance ResistanceCold ResistanceCreationCryokinesisCurse ResistanceDark ArtsDark MagicDarkforce ManipulationDeath ManipulationDeath TouchDexterityDuplicationDurabilityDurability NegationElectricity ResistanceElectrokinesisElement ControlElemental TransmogrificationEnduranceEnergy AbsorptionEnergy BlastsEnergy ConstructsEnergy ManipulationEnergy ResistanceEnhanced HearingEnhanced MemoryEnhanced SensesEnhanced SightEnhanced SmellEnhanced TouchExtrasensory PerceptionFear ManipulationFire ControlFire ResistanceFlightForce FieldsGodly PhysiologyHeat GenerationHeat ResistanceHellfire ResistanceImmortalityIntangibilityIntelligenceInvulnerabilityLevitationLight ControlMagicMagic AbsorptionMagic ResistanceMind ControlNon-CorporealNon-Physical InteractionNothingness Aspect ManifestationParalysisPetrificationPortal CreationPossession ResistancePower AbsorptionPower NullifierProbability ManipulationReflexesRegenerationResurrectionShapeshiftingSoul ManipulationSoul ResistanceSpaceflightStaminaStatistics AmplificationStatistics ReductionStatus Effect InducementTelepathy ResistanceTeleportationTerrakinesisTime Manipulation ResistanceToxin and Disease ControlToxin and Disease ResistanceWater ControlAnti-GravityCorruption ResistanceCurse ManipulationDamage BoostDamage ReductionDamage TransferalElectricity AbsorptionEmpathyFear InducementGravity ControlHoly ManipulationHoly ResistanceIllusion ResistanceIllusionsLife ManipulationMatter AbsorptionMemory ManipulationMind Control ResistancePossessionPower Absorption ImmunityPurificationRadiation AbsorptionReality Warping ResistanceSleep ManipulationSound ManipulationTransmutationUnholy Resistance', 34000000);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Killer Frost', 'Louise Lincoln', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/louise-lincoln-8750552096404621465.jpg', 'CryokinesisEnergy AbsorptionIntelligenceSummoningAcrobaticsAuraCold ResistanceElement ControlFire ResistanceGlidingHeat ResistanceMarksmanshipMaster Martial Artist', 35);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Master Man', 'Wilhelm Lohmer', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/wilhelm-lohmer-3771337271614718448.jpg', 'DurabilityEnhanced HearingEnhanced SensesEnhanced SightEnhanced SmellEnhanced TouchMarksmanshipStaminaSuper SpeedSuper StrengthWeapon-based PowersWeapons MasterAcrobaticsAgilityDexterityReflexesAccelerated HealingCold ResistanceEnergy ResistanceFire ResistanceHeat ResistanceJumpLongevityPsionic PowersRadiation ImmunityRegenerationSelf-SustenanceToxin and Disease Resistance', 92);
INSERT INTO villain(id, name, otherName, picture, powers, level)
VALUES (nextval('hibernate_sequence'), 'Wrath', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/wrath-5110862576269869358.jpg', 'Accelerated HealingCold ResistanceDurabilityElectricity ResistanceEnduranceEnergy ResistanceFire ResistanceHeat ResistanceIntelligenceInvulnerabilityRadiation ImmunityReflexesRegenerationSelf-SustenanceStaminaStealthSuper SpeedSuper StrengthToxin and Disease ResistanceAgilityDexterityFlightImmortalityJump', 1000);
