CREATE ROLE super WITH LOGIN PASSWORD 'super';

CREATE ROLE superfight WITH LOGIN PASSWORD 'superfight' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
CREATE DATABASE fights_database;
GRANT ALL PRIVILEGES ON DATABASE fights_database TO superfight;
GRANT ALL PRIVILEGES ON DATABASE fights_database TO super;
