name: Deploy documentation site

on:
  workflow_run:
    workflows: ["Basic build and test"]
    types:
      - completed
    branches:
      - main

  workflow_dispatch:

concurrency:
  group: pages
  cancel-in-progress: false

defaults:
  run:
    working-directory: docs
    shell: bash

permissions:
  pages: write
  id-token: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    if: github.repository == 'quarkusio/quarkus-super-heroes' && (github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success')
    steps:
      - uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5.2.0
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: Generate Roq site
        env:
          QUARKUS_ROQ_GENERATOR_BATCH: true
        run: |
          ./mvnw -B package quarkus:run \
            -DskipTests \
            -Dquarkus.http.root-path=/quarkus-super-heroes \
            -Dsite.url=https://quarkus.io

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v6

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: docs/target/roq

  deploy-docs:
    needs: build-docs
    runs-on: ubuntu-latest
    if: github.repository == 'quarkusio/quarkus-super-heroes'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
